const test=require('node:test'),assert=require('node:assert/strict');
const C=require('../public/core.js');
const today=C.localDate();
function account(s,name='Bank',opening=100000,kind='bank'){return C.apply(s,{type:'account.add',name,opening,kind,color:'sand'})}
function base(){let s=account(C.blank());s=account(s,'Cash',10000,'cash');return s}
function entry(s,kind,amount,more={}){return C.apply(s,{type:'transaction.add',kind,amount,account:s.accounts[0].id,date:today,category:kind==='income'?'Salary':'Other',note:'',...more})}
function goal(s,target=50000,name='Travel'){return C.apply(s,{type:'goal.add',name,target,icon:'plane',color:'sage',note:'',deadline:''})}
function allocate(s,amount,more={}){return C.apply(s,{type:'goal.allocate',id:s.goals[0].id,account:s.accounts[0].id,amount,...more})}

test('parses AED precisely into integer fils',()=>{assert.equal(C.money('0.10'),10);assert.equal(C.money('1,250.50'),125050);assert.equal(C.money('AED 25'),2500);assert.equal(C.money('٠٫٢٥'),25);assert.equal(C.money('۱۲۳.۴۵'),12345)});
test('rejects malformed commas, excess decimals, NaN and oversized amounts',()=>{for(const x of ['1,00','0.001','NaN','Infinity','1e3','999999999999999999','-5'])assert.throws(()=>C.money(x));assert.throws(()=>C.money('0'));assert.equal(C.money('0',{zero:true}),0)});
test('new workspace has no fabricated finances',()=>{const s=C.blank();assert.equal(s.accounts.length,0);assert.equal(s.transactions.length,0);assert.equal(s.goals.length,0);assert.equal(C.summary(s).total,0);assert.doesNotThrow(()=>C.validate(s))});
test('opening balances count as money but not monthly income',()=>{const m=C.summary(base());assert.equal(m.total,110000);assert.equal(m.income,0);assert.equal(m.spent,0)});
test('income and expense update exactly once',()=>{let s=base();s=entry(s,'income',50000);s=entry(s,'expense',2500);const m=C.summary(s);assert.equal(m.total,157500);assert.equal(m.income,50000);assert.equal(m.spent,2500);assert.equal(m.net,47500)});
test('transfer preserves total and does not inflate income or spending',()=>{let s=base();s=entry(s,'transfer',25000,{to:s.accounts[1].id});const m=C.summary(s);assert.equal(m.total,110000);assert.equal(m.balances[s.accounts[0].id],75000);assert.equal(m.balances[s.accounts[1].id],35000);assert.equal(m.income,0);assert.equal(m.spent,0)});
test('rejects same-account transfers, missing accounts and future entries',()=>{const s=base();assert.throws(()=>entry(s,'transfer',1,{to:s.accounts[0].id}));assert.throws(()=>entry(s,'transfer',1,{to:'missing'}));assert.throws(()=>entry(s,'expense',1,{account:'absent'}));assert.throws(()=>entry(s,'expense',1,{date:'2999-01-01'}))});
test('negative account balances are blocked without mutating source state',()=>{const s=base(),snapshot=JSON.stringify(s);assert.throws(()=>entry(s,'expense',100001));assert.equal(JSON.stringify(s),snapshot)});
test('goals reserve existing money without creating money',()=>{let s=goal(base());s=allocate(s,20000);const m=C.summary(s);assert.equal(m.total,110000);assert.equal(m.reserved,20000);assert.equal(m.available,90000);assert.equal(m.balances[s.accounts[0].id],100000)});
test('the same account money cannot be reserved twice across goals',()=>{let s=goal(base(),100000,'Car');s=allocate(s,90000);s=goal(s,50000,'Travel');assert.throws(()=>allocate(s,20000,{id:s.goals[1].id}));assert.equal(C.summary(s).reserved,90000)});
test('reserved money cannot be spent or transferred until released',()=>{let s=allocate(goal(base()),50000);assert.throws(()=>entry(s,'expense',60000));assert.throws(()=>entry(s,'transfer',60000,{to:s.accounts[1].id}));assert.doesNotThrow(()=>entry(s,'expense',50000))});
test('goal release frees money in the selected account only',()=>{let s=allocate(goal(base()),30000);s=allocate(s,5000,{account:s.accounts[1].id});s=C.apply(s,{type:'goal.release',id:s.goals[0].id,account:s.accounts[0].id,amount:10000});const m=C.summary(s);assert.equal(m.reserved,25000);assert.equal(m.reserves[s.accounts[1].id],5000);assert.equal(m.total,110000);assert.throws(()=>C.apply(s,{type:'goal.release',id:s.goals[0].id,account:s.accounts[1].id,amount:5001}))});
test('allocation cannot exceed target or use negative amounts',()=>{let s=goal(base(),5000);assert.throws(()=>allocate(s,5001));assert.throws(()=>allocate(s,-1))});
test('removing a goal releases its allocation without deleting account money',()=>{let s=allocate(goal(base()),20000);s=C.apply(s,{type:'goal.delete',id:s.goals[0].id});assert.equal(C.summary(s).reserved,0);assert.equal(C.summary(s).total,110000)});
test('cannot lower goal target below already saved money',()=>{let s=allocate(goal(base()),20000),g=s.goals[0];assert.throws(()=>C.apply(s,{type:'goal.edit',...g,target:19999}))});
test('goal plan handles completed goals, deadlines and overdue dates',()=>{let s=allocate(goal(base(),20000),20000),g=s.goals[0];assert.equal(C.goalPlan(g).progress,100);assert.equal(C.goalPlan(g).remaining,0);g={...g,target:60000,deadline:'2026-12-31'};const plan=C.goalPlan(g,'2026-09-22');assert.equal(plan.months,4);assert.equal(plan.perMonth,10000);assert.equal(C.goalPlan(g,'2027-01-01').overdue,true)});
test('balance corrections are excluded from income and spending',()=>{let s=base();s=C.apply(s,{type:'account.reconcile',id:s.accounts[0].id,balance:75000});const m=C.summary(s);assert.equal(m.total,85000);assert.equal(m.income,0);assert.equal(m.spent,0);assert.equal(s.transactions[0].amount,-25000)});
test('balance correction cannot consume goal reservations',()=>{const s=allocate(goal(base()),50000);assert.throws(()=>C.apply(s,{type:'account.reconcile',id:s.accounts[0].id,balance:49999}))});
test('editing an expense replaces rather than duplicates its effect',()=>{let s=entry(base(),'expense',10000),t=s.transactions[0];s=C.apply(s,{type:'transaction.edit',id:t.id,kind:'expense',amount:5000,account:t.account,note:'edited',category:'Other',date:today});assert.equal(s.transactions.length,1);assert.equal(C.summary(s).total,105000);assert.equal(C.summary(s).spent,5000)});
test('deleting a transfer reverses both sides',()=>{let s=base();s=entry(s,'transfer',30000,{to:s.accounts[1].id});s=C.apply(s,{type:'transaction.delete',id:s.transactions[0].id});assert.equal(C.balances(s)[s.accounts[0].id],100000);assert.equal(C.balances(s)[s.accounts[1].id],10000)});
test('deleting supporting income cannot create an unfunded balance',()=>{let s=entry(base(),'income',20000),incomeId=s.transactions[0].id;s=entry(s,'expense',110000);assert.throws(()=>C.apply(s,{type:'transaction.delete',id:incomeId}))});
test('referenced accounts cannot be deleted and account names are unique',()=>{let s=entry(base(),'expense',100);assert.throws(()=>C.apply(s,{type:'account.delete',id:s.accounts[0].id}));assert.throws(()=>account(s,'BANK'));assert.doesNotThrow(()=>C.apply(s,{type:'account.delete',id:s.accounts[1].id}))});
test('backup round trip preserves exact account and goal totals',()=>{let s=allocate(goal(entry(base(),'income',12345)),33333);const round=C.validate(JSON.parse(JSON.stringify(s)));assert.deepEqual(C.summary(round),C.summary(s));assert.equal(C.goalSaved(round.goals[0]),33333)});
test('corrupted backups with dangling accounts or duplicate IDs fail',()=>{const s=entry(base(),'expense',50);let bad=C.clone(s);bad.transactions[0].account='not-here';assert.throws(()=>C.validate(bad));bad=C.clone(s);bad.accounts.push(C.clone(bad.accounts[0]));assert.throws(()=>C.validate(bad));bad=C.clone(s);bad.accounts[0].opening=.1;assert.throws(()=>C.validate(bad))});
test('backup cannot introduce overfunding or invalid dates',()=>{const s=allocate(goal(base()),10000);let bad=C.clone(s);bad.goals[0].allocations[0].amount=99999999;assert.throws(()=>C.validate(bad));bad=C.clone(s);bad.goals[0].deadline='2026-02-30';assert.throws(()=>C.validate(bad))});
test('all four arithmetic operations and precedence are exact',()=>{for(const [q,a] of [['12 + 8','20'],['40-13','27'],['7*9','63'],['120/8','15'],['2+3*4','14'],['(2500 - 350) / 5','430'],['0.1+0.2','0.3'],['1.005*100','100.5'],['-3 * -4','12'],['2--3','5']])assert.equal(C.calc(q).text,a,q)});
test('calculator accepts spoken operations, grouping and Arabic digits',()=>{for(const [q,a] of [['what is 200 divided by 4?','50'],['5 plus 6 times 2','17'],['١٢ ÷ ٤','3'],['1,250.50 - 250.50','1000'],['.5 + .25','0.75'],['20 percent of 250','50'],['15% * 200','30']])assert.equal(C.calc(q).text,a,q)});
test('division by zero and nonfinite or code inputs are rejected',()=>{for(const q of ['5/0','0/0','process.exit()','alert(1)','1;2','Infinity+2','2**3','2 +','(2+3','2(3+4)','1,00+2'])assert.throws(()=>C.calc(q),q)});
test('division precision is labelled and rounding is deterministic',()=>{assert.deepEqual(C.calc('1/3'),{text:'0.3333333333',approximate:true,expression:'1/3'});assert.equal(C.calc('2/3').text,'0.6666666667');assert.equal(C.calc('-1/3').text,'-0.3333333333');assert.equal(C.calc('1/8').approximate,false)});
test('calculator limits resource-heavy input',()=>{assert.throws(()=>C.calc('1+'.repeat(100)+'1'));assert.throws(()=>C.calc('12345678901234567+1'))});
test('assistant reports actual state with no fabricated amounts',()=>{const s=base(),reply=C.assistant(s,'balance');assert.match(reply.text,/1,100.00/);assert.match(reply.text,/Bank: AED 1,000.00/);assert(!reply.draft);assert.match(C.assistant(C.blank(),'balance').text,/Add your first account/)});
test('assistant prepares an expense without committing it',()=>{const s=base(),snapshot=JSON.stringify(s),reply=C.assistant(s,'expense 25 from Cash for coffee');assert.equal(reply.draft.kind,'expense');assert.equal(reply.draft.amount,2500);assert.equal(reply.draft.account,s.accounts[1].id);assert.equal(reply.draft.category,'Food & drink');assert.equal(JSON.stringify(s),snapshot)});
test('assistant prepares income, transfer and goal savings',()=>{const s=goal(base());assert.equal(C.assistant(s,'income 500 to Bank for allowance').draft.category,'Allowance');const t=C.assistant(s,'transfer 200 from Bank to Cash').draft;assert.equal(t.to,s.accounts[1].id);const g=C.assistant(s,'save 100 to Travel from Bank').draft;assert.equal(g.id,s.goals[0].id);assert.equal(g.amount,10000)});
test('assistant rejects unknown account names and unsupported requests clearly',()=>{const s=base();assert.equal(C.assistant(s,'expense 25 from Wrong bank for coffee').error,true);assert.match(C.assistant(s,'what stock should I buy').text,/simple entries/);assert.equal(C.assistant(s,'1/0').error,true)});
test('demo data is valid, separate and explicitly created on demand',()=>{const blank=C.blank(),demo=C.demo();C.validate(demo);assert.equal(blank.accounts.length,0);assert.equal(demo.accounts.length,3);assert.equal(demo.goals.length,2);assert.equal(C.summary(demo).total,2065200)});
test('invalid month aggregates cannot overflow the money range',()=>{let s=account(C.blank(),'Bank',0);s=entry(s,'income',C.MAX_MONEY);s=entry(s,'expense',C.MAX_MONEY);assert.throws(()=>entry(s,'income',1))});
test('valid dates check actual calendar days',()=>{assert(C.validDate('2024-02-29'));assert(!C.validDate('2025-02-29'));assert(!C.validDate('2026-13-01'));assert(!C.validDate('2026-9-1'))});
