const test=require('node:test'),assert=require('node:assert/strict'),C=require('../public/core.js'),B=require('../public/backups.js');
function seed(){let s=C.blank();for(const name of ['Main','Cash'])s=C.apply(s,{type:'account.add',name,kind:'bank',opening:1000000});s.undoHistory=[];return s}
function entry(s,extra={}){return {type:'transaction.add',kind:'expense',account:s.accounts[0].id,amount:3000,date:'2026-08-18',category:'Laundry',...extra}}
function undo(s){return C.apply(s,{type:'undo',id:s.undoHistory.at(-1).id})}
function schedule(s,extra={}){return C.apply(s,{type:'recurring.save',name:'Monthly bill',kind:'expense',category:'Bills',account:s.accounts[0].id,amount:3000,frequency:'monthly',nextDate:'2026-08-18',...extra})}
const ledger=s=>({accounts:s.accounts,cards:s.cards,goals:s.goals,transactions:s.transactions,recurring:s.recurring||[]});
test('undo reverses add, edit and delete with exact IDs and balances while retaining unrelated preferences',()=>{const original=seed();let s=C.apply(original,entry(original));const added=C.clone(s),t=s.transactions[0];s=C.apply(s,{...entry(s),type:'transaction.edit',id:t.id,amount:3700,note:'Changed'});s=undo(s);assert.deepEqual(ledger(s),ledger(added));s=C.apply(s,{type:'transaction.delete',id:t.id});s=C.apply(s,{type:'settings',name:'Family member',theme:'night',language:'ar',textSize:'larger'});s=undo(s);assert.deepEqual(s.transactions,added.transactions);assert.equal(s.settings.name,'Family member');assert.equal(s.settings.language,'ar');s=undo(s);assert.deepEqual(ledger(s),ledger(original));assert.equal(s.settings.theme,'night');assert(s.changeCounter>added.changeCounter)});
test('undo restores a split as one original transaction and keeps aggregate money identical',()=>{let s=seed();s=C.apply(s,entry(s));const before=C.clone(s);s=C.apply(s,{type:'transaction.split',id:s.transactions[0].id,amount:1500,date:'2026-07-18'});assert.equal(s.transactions.length,2);s=undo(s);assert.deepEqual(ledger(s),ledger(before))});
test('undo refuses stale IDs and modified affected records without partial mutation',()=>{let s=seed();s=C.apply(s,entry(s));const id=s.undoHistory.at(-1).id;s=C.apply(s,entry(s,{amount:4000}));assert.throws(()=>C.apply(s,{type:'undo',id}),/latest change/);s.transactions.at(-1).note='External change';const old=JSON.stringify(s);assert.throws(()=>undo(s),/Related records/);assert.equal(JSON.stringify(s),old)});
test('undo never deletes an account now referenced by a favourite',()=>{let s=seed();s=C.apply(s,{type:'account.add',name:'New',opening:5000,kind:'bank'});s=C.apply(s,{type:'favourite.save',name:'Laundry',amount:3000,category:'Laundry',account:s.accounts.at(-1).id});const old=JSON.stringify(s);assert.throws(()=>undo(s));assert.equal(JSON.stringify(s),old)});
test('undo journal is bounded and start/reset establish a new boundary',()=>{let s=seed();for(let i=0;i<30;i++)s=C.apply(s,entry(s,{amount:i+1}));assert.equal(s.undoHistory.length,20);for(let i=0;i<20;i++)s=undo(s);assert.equal(s.transactions.length,10);assert.equal(s.undoHistory.length,0);s=C.apply(s,{type:'tracking.start',expectedRev:s.rev,balances:s.accounts.map(a=>({id:a.id,balance:C.balances(s)[a.id]}))});assert.equal(s.undoHistory.length,0);assert.equal(C.resetMoney(s).undoHistory,undefined)});
test('duplicates cover nearby equal payments, close values, and repeated salary in the month',()=>{let s=seed();s=C.apply(s,entry(s));assert.equal(C.possibleDuplicates(s,entry(s,{date:'2026-08-21'})).length,1);assert.equal(C.possibleDuplicates(s,entry(s,{amount:3050,date:'2026-08-19'})).length,1);assert.equal(C.possibleDuplicates(s,entry(s,{date:'2026-08-22'})).length,0);assert.equal(C.possibleDuplicates(s,entry(s,{account:s.accounts[1].id})).length,0);assert.equal(C.possibleDuplicates(s,entry(s,{kind:'income',category:'Salary'})).length,0);assert.equal(C.possibleDuplicates(s,entry(s,{id:s.transactions[0].id})).length,0);s=C.apply(s,entry(s,{kind:'income',category:'Salary',amount:800000,date:'2026-08-01'}));assert.equal(C.possibleDuplicates(s,entry(s,{kind:'income',category:'Salary',amount:800000,date:'2026-08-29'})).length,1)});
test('guarded duplicates require acknowledgement of every current match and never write on warning',()=>{let s=seed();s=C.apply(s,entry(s));const before=JSON.stringify(s),a=entry(s,{checkDuplicates:true});let tokens;assert.throws(()=>C.apply(s,a),e=>{tokens=e.tokens;return e.code==='POSSIBLE_DUPLICATE'});assert.equal(JSON.stringify(s),before);s=C.apply(s,{...a,acknowledgedDuplicates:tokens});assert.equal(s.transactions.length,2);assert.throws(()=>C.apply(s,{...a,acknowledgedDuplicates:tokens}),e=>e.code==='POSSIBLE_DUPLICATE')});
test('matching a bill preserves its existing amount/date and balance; undo restores pending review',()=>{let s=seed();s=C.apply(s,entry(s,{amount:3200,date:'2026-08-20',category:'Bills'}));s=schedule(s);const before=C.clone(s),r=s.recurring[0],t=s.transactions[0];assert.equal(C.recurringMatches(s,r.id)[0].id,t.id);s=C.apply(s,{type:'recurring.match',id:r.id,dueDate:r.nextDate,transaction:t.id});assert.equal(s.transactions.length,1);assert.equal(s.transactions[0].amount,3200);assert.equal(s.transactions[0].date,'2026-08-20');assert.equal(s.transactions[0].recurringId,r.id);assert.deepEqual(C.balances(s),C.balances(before));assert.equal(s.recurring[0].nextDate,'2026-09-18');assert.equal(C.recurringMatches(s,r.id).length,0);s=undo(s);assert.deepEqual(ledger(s),ledger(before))});
test('matching rejects mismatched accounts, types, reused entries and stale occurrences atomically',()=>{let s=seed();s=C.apply(s,entry(s,{account:s.accounts[1].id}));s=C.apply(s,entry(s,{kind:'income',category:'Salary'}));s=C.apply(s,entry(s));s=schedule(s);const r=s.recurring[0];for(const t of s.transactions.slice(0,2))assert.throws(()=>C.apply(s,{type:'recurring.match',id:r.id,dueDate:r.nextDate,transaction:t.id}),/same type/);const a={type:'recurring.match',id:r.id,dueDate:r.nextDate,transaction:s.transactions[2].id};s=C.apply(s,a);assert.throws(()=>C.apply(s,a),/no longer/);s=schedule(s,{name:'Second bill'});const other=s.recurring[1];assert.throws(()=>C.apply(s,{...a,id:other.id,dueDate:other.nextDate}),/already linked/)});
test('recurring record duplicate warning leaves schedule pending and creates one undo step on confirmation',()=>{let s=seed();s=C.apply(s,entry(s,{category:'Bills'}));s=schedule(s);const r=s.recurring[0],before=C.clone(s),a={type:'recurring.record',id:r.id,dueDate:r.nextDate,amount:r.amount,account:r.account,date:r.nextDate,checkDuplicates:true};assert.throws(()=>C.apply(s,a),e=>e.code==='POSSIBLE_DUPLICATE');assert.deepEqual(s,before);s=C.apply(s,{...a,acknowledgedDuplicates:s.transactions.map(C.duplicateToken)});assert.equal(s.undoHistory.length,before.undoHistory.length+1);s=undo(s);assert.deepEqual(ledger(s),ledger(before))});
test('favourites preserve account/card/category without recording money and round-trip encrypted backups',async()=>{let s=seed();s=C.apply(s,{type:'card.add',account:s.accounts[0].id,name:'Everyday debit'});s=C.apply(s,{type:'favourite.save',name:'Weekly laundry',amount:3000,category:'Laundry',account:s.accounts[0].id,card:s.cards[0].id,note:'Usual wash'});assert.equal(s.transactions.length,0);assert.equal(C.summary(s).total,2000000);const f=s.favourites[0];assert.throws(()=>C.apply(s,{type:'card.delete',id:s.cards[0].id}),/favourites/);assert.throws(()=>C.apply(s,{type:'favourite.save',...f,id:undefined,name:'weekly LAUNDRY'}),/already exists/);s=C.apply(s,{type:'favourite.save',...f,amount:3500});const backup=await B.create(s,{password:'family synthetic backup'});const decoded=await B.decode(backup.text,'family synthetic backup');assert.deepEqual(decoded.favourites,s.favourites);s=C.apply(s,{type:'favourite.delete',id:f.id});assert.equal(s.favourites.length,0);assert.equal(s.transactions.length,0)});
test('invalid favourite references, categories and amounts are rejected',()=>{const s=seed(),base={type:'favourite.save',name:'Laundry',amount:3000,category:'Laundry',account:s.accounts[0].id};for(const patch of [{account:'missing'},{category:'Salary'},{category:'Unexplained'},{amount:0},{card:'missing'}])assert.throws(()=>C.apply(s,{...base,...patch}));assert.equal(s.favourites,undefined)});
test('backup reminders require matching current verification, respect snooze and count only relevant changes',async()=>{let s=seed();assert.equal(C.backupReminder(s).reason,'first');const now=Date.now(),record={filename:'test.json',encrypted:false,at:now,revision:s.rev,digest:'a'.repeat(64)};s=C.apply(s,{type:'backup.exported',record});assert.equal(C.backupReminder(s).reason,'first');s=C.apply(s,{type:'backup.verified',record,current:false,expectedRev:s.rev});assert.equal(C.backupReminder(s).reason,'first');s=C.apply(s,{type:'backup.verified',record,current:true,expectedRev:s.rev-1});assert.equal(C.backupReminder(s).reason,'first');s=C.apply(s,{type:'backup.verified',record,current:true,expectedRev:s.rev});assert.equal(C.backupReminder(s),null);const count=s.changeCounter;s=C.apply(s,{type:'settings',language:'ar',textSize:'large',backupReminderChanges:10});assert.equal(s.changeCounter,count);for(let i=0;i<10;i++)s=C.apply(s,entry(s,{amount:i+1}));assert.equal(C.backupReminder(s).reason,'changes');s=C.apply(s,{type:'backup.snooze'});assert.equal(C.backupReminder(s),null);assert.equal(C.backupReminder(s,Date.now()+86400001).reason,'changes');s=C.apply(s,{type:'settings',backupReminders:false});assert.equal(C.backupReminder(s,Date.now()+999999999),null)});
test('time reminders fire at configured interval and a current digest ignores bookkeeping but detects changes',async()=>{let s=seed(),digest=await B.contentDigest(s);s=C.apply(s,{type:'settings',language:'ar',textSize:'larger',backupReminderDays:3});s.settings.backupBaseline={at:1000,counter:s.changeCounter};assert.equal(C.backupReminder(s,1000+3*86400000-1),null);assert.equal(C.backupReminder(s,1000+3*86400000).reason,'time');assert.equal(await B.contentDigest(s),digest);s=C.apply(s,{type:'favourite.save',name:'Laundry',amount:3000,category:'Laundry',account:s.accounts[0].id});assert.notEqual(await B.contentDigest(s),digest);const result=await B.inspect(JSON.stringify(s),'','test.json');assert.equal(result.record.contentDigest,await B.contentDigest(s));s=schedule(s);assert.notEqual(await B.contentDigest(s),result.record.contentDigest)});
