const test=require('node:test'),assert=require('node:assert/strict'),C=require('../public/core.js');
function setup(){let s=C.blank();s=C.apply(s,{type:'account.add',name:'Bank',kind:'bank',opening:200000,color:'sand'});s=C.apply(s,{type:'account.add',name:'Portfolio',kind:'investment',opening:0,color:'sage'});return s}
function add(s,extra={}){return C.apply(s,{type:'holding.add',account:s.accounts[1].id,name:'Example company',quantity:'400',cost:100000,value:100000,mode:'transfer',source:s.accounts[0].id,...extra})}
test('buying shares preserves wealth and records no spending or salary',()=>{const s=add(setup()),m=C.summary(s);assert.equal(m.total,200000);assert.equal(m.balances[s.accounts[0].id],100000);assert.equal(m.balances[s.accounts[1].id],100000);assert.equal(C.holdingsValue(s.accounts[1]),100000);assert.equal(s.accounts[1].holdings[0].quantity,'400');assert.equal(m.spent,0);assert.equal(m.income,0);assert.equal(C.spendingBreakdown(s).invested,100000)});
test('multiple companies share one portfolio and included holdings add no extra wealth',()=>{let s=setup();s=C.apply(s,{type:'transaction.add',kind:'transfer',account:s.accounts[0].id,to:s.accounts[1].id,amount:150000,date:C.localDate()});s=add(s,{mode:'included'});s=add(s,{name:'Second company',quantity:'20.5',cost:50000,value:50000,mode:'included'});assert.equal(C.summary(s).total,200000);assert.equal(s.accounts[1].holdings.length,2);assert.throws(()=>add(s,{mode:'included'}));assert.equal(C.canSetOpening(s,s.accounts[1].id),false)});
test('unrecorded assets add value once and valuation updates change only the difference',()=>{let s=add(setup(),{mode:'unrecorded'});assert.equal(C.summary(s).total,300000);const h=s.accounts[1].holdings[0];s=C.apply(s,{type:'holding.edit',account:s.accounts[1].id,id:h.id,name:h.name,quantity:h.quantity,cost:h.cost,value:120000});assert.equal(C.summary(s).total,320000);assert.equal(C.summary(s).income,0);assert.equal(C.summary(s).spent,0);assert.equal(C.holdingsValue(s.accounts[1]),120000);assert.deepEqual(C.validate(JSON.parse(JSON.stringify(s))),s)});
test('selling all shares leaves net proceeds as portfolio cash',()=>{let s=add(setup());s=C.apply(s,{type:'holding.sell',account:s.accounts[1].id,id:s.accounts[1].holdings[0].id,proceeds:110000});assert.equal(C.summary(s).total,210000);assert.equal(C.holdingsValue(s.accounts[1]),0);assert.equal(C.balances(s)[s.accounts[1].id],110000);assert.equal(C.summary(s).spent,0);assert.equal(C.summary(s).income,0)});
test('holdings protect backing value, account type and generated transaction records',()=>{const s=add(setup()),before=JSON.stringify(s);assert.throws(()=>C.apply(s,{type:'transaction.add',kind:'transfer',amount:100,account:s.accounts[1].id,to:s.accounts[0].id,date:C.localDate()}));assert.throws(()=>C.apply(s,{type:'account.edit',id:s.accounts[1].id,name:'Portfolio',kind:'cash'}));assert.throws(()=>C.apply(s,{type:'transaction.delete',id:s.transactions[0].id}));assert.equal(JSON.stringify(s),before)});
test('removing holding details preserves account value; reset clears quantities and values',()=>{const s=add(setup());const removed=C.apply(s,{type:'holding.remove',account:s.accounts[1].id,id:s.accounts[1].holdings[0].id});assert.equal(C.summary(removed).total,200000);const reset=C.resetMoney(s);assert.equal(C.summary(reset).total,0);assert.equal(C.holdingsValue(reset.accounts[1]),0);assert.equal(reset.accounts[1].name,'Portfolio')});
test('moving an already valued account supports original cost differing from transferred value',()=>{const s=add(setup(),{cost:80000,value:100000,funding:100000});assert.equal(C.summary(s).total,200000);assert.equal(s.accounts[1].holdings[0].cost,80000)});
test('invalid quantities and insufficient funds are rejected atomically',()=>{const s=setup(),before=JSON.stringify(s);for(const quantity of ['0','-1','NaN','0.0000001'])assert.throws(()=>add(s,{quantity}));assert.throws(()=>add(s,{cost:300000,value:300000}));assert.equal(JSON.stringify(s),before);assert.equal(C.shareQuantity('٠.٥'),'0.5')});
