const test=require('node:test'),assert=require('node:assert/strict'),C=require('../public/core.js');
const today=C.localDate(),previous=C.localDate(new Date(new Date().getFullYear(),new Date().getMonth()-1,15));
function seed(category='Unexplained',kind='expense'){
 let s=C.apply(C.blank(),{type:'account.add',name:'Bank',kind:'bank',opening:1000000});
 s=C.apply(s,{type:'card.add',name:'Debit',account:s.accounts[0].id,last4:'1234'});
 s=C.apply(s,{type:'goal.add',name:'China trip',target:500000});
 s=C.apply(s,{type:'goal.allocate',id:s.goals[0].id,account:s.accounts[0].id,amount:200000});
 return C.apply(s,{type:'transaction.add',kind,amount:450000,account:s.accounts[0].id,card:kind==='expense'?s.cards[0].id:null,date:today,category,note:'Example entry'});
}
function split(s,amount=150000,date=previous,id=s.transactions[0].id){return C.apply(s,{type:'transaction.split',id,amount,date})}
test('split AED 4500 into AED 3000 this month and AED 1500 last month, preserving balances and goals',()=>{const old=seed(),before=JSON.stringify(old),s=split(old),now=C.summary(s),last=C.summary(s,previous);assert.equal(now.spent,300000);assert.equal(now.unknownSpent,300000);assert.equal(last.spent,150000);assert.equal(last.unknownSpent,150000);assert.equal(now.spent+last.spent,450000);assert.deepEqual(C.balances(s),C.balances(old));assert.deepEqual(C.reserves(s),C.reserves(old));assert.deepEqual(s.goals,old.goals);assert.equal(JSON.stringify(old),before);assert.equal(s.transactions[0].id,old.transactions[0].id);assert.equal(s.transactions[0].date,today);assert.equal(s.transactions[1].date,previous)});
test('splitting known card spending preserves category, account, card, note and total',()=>{const before=seed('Shopping'),s=split(before,100001);for(const t of s.transactions){assert.equal(t.category,'Shopping');assert.equal(t.card,before.cards[0].id);assert.equal(t.account,before.accounts[0].id);assert.equal(t.note,'Example entry')}assert.equal(C.summary(s).knownSpent,349999);assert.equal(C.summary(s,previous).knownSpent,100001);assert.equal(C.summary(s).total,C.summary(before).total)});
test('repeat partial splits preserve exact fils, unique IDs and total spending',()=>{const before=seed();let s=split(before,1);s=split(s,10002);assert.equal(new Set(s.transactions.map(t=>t.id)).size,3);assert.equal(C.summary(s).spent,439997);assert.equal(C.summary(s,previous).spent,10003);assert.equal(s.transactions.reduce((n,t)=>n+t.amount,0),450000);assert.deepEqual(C.balances(s),C.balances(before))});
test('split income changes monthly income and salary without adding or subtracting money',()=>{const before=seed('Salary','income'),s=split(before);assert.equal(C.summary(s).salary,300000);assert.equal(C.summary(s,previous).salary,150000);assert.equal(C.summary(s).spent,0);assert.deepEqual(C.balances(s),C.balances(before))});
test('invalid split amounts, dates and unknown IDs leave original data untouched',()=>{const s=seed(),snapshot=JSON.stringify(s);for(const n of [0,-1,450000,450001,1.5,NaN])assert.throws(()=>split(s,n));for(const d of ['',null,'2999-01-01','2026-02-30'])assert.throws(()=>split(s,100,d));assert.throws(()=>split(s,100,previous,'absent'));assert.equal(JSON.stringify(s),snapshot)});
test('transfers and corrections cannot be split',()=>{let s=seed();s=C.apply(s,{type:'account.add',name:'Cash',kind:'cash',opening:0});s=C.apply(s,{type:'transaction.add',kind:'transfer',amount:100,account:s.accounts[0].id,to:s.accounts[1].id,date:today});assert.throws(()=>split(s,50,previous,s.transactions.at(-1).id));s=C.apply(s,{type:'account.reconcile',id:s.accounts[0].id,balance:C.balances(s)[s.accounts[0].id]+100});assert.throws(()=>split(s,50,previous,s.transactions.at(-1).id))});
test('splitting a balance-check gap then rechecking creates no duplicate spending',()=>{let s=C.apply(C.blank(),{type:'account.add',name:'Bank',kind:'bank',opening:1000000});s=C.apply(s,{type:'account.check',id:s.accounts[0].id,balance:550000});s=split(s);const count=s.transactions.length;s=C.apply(s,{type:'account.check',id:s.accounts[0].id,balance:550000});assert.equal(s.transactions.length,count);assert.equal(C.summary(s).total,550000);assert.equal(C.summary(s,previous).unknownSpent,150000);assert.equal(s.transactions[1].balanceCheck,undefined)});
test('explaining unknown spending can choose its original date without another debit',()=>{const before=seed();const s=C.apply(before,{type:'transaction.explain',id:before.transactions[0].id,amount:150000,date:previous,category:'Transport'});assert.equal(C.summary(s).unknownSpent,300000);assert.equal(C.summary(s,previous).knownSpent,150000);assert.deepEqual(C.balances(s),C.balances(before));assert.throws(()=>C.apply(before,{type:'transaction.explain',id:before.transactions[0].id,amount:150000,date:'2999-01-01',category:'Transport'}))});
test('existing explanation commands without a date retain their original date',()=>{const before=seed();const s=C.apply(before,{type:'transaction.explain',id:before.transactions[0].id,amount:150000,category:'Transport'});assert(s.transactions.every(t=>t.date===today));assert.equal(C.summary(s).spent,450000)});
test('existing version-1 data remains valid unchanged and split backups round-trip',()=>{const old=seed(),json=JSON.stringify(old);assert.equal(C.VERSION,1);assert.equal(JSON.stringify(C.validate(JSON.parse(json))),json);const s=split(old),round=C.validate(JSON.parse(JSON.stringify(s)));assert.deepEqual(C.balances(round),C.balances(old));assert.deepEqual(C.summary(round,previous),C.summary(s,previous))});
