const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'../public');
function environment(scope='https://example.test/dirhaya/'){
 const listeners={},stores=new Map();let claimed=false,skipped=false,network=0;
 const caches={async open(name){if(!stores.has(name))stores.set(name,new Map());const store=stores.get(name);return {async addAll(urls){for(const request of urls){assert.equal(request.cache,'reload');const u=request.url;const relative=u.slice(scope.length)||'index.html';assert(fs.existsSync(path.join(root,relative)),relative+' must exist');store.set(u,{ok:true,url:u,body:fs.readFileSync(path.join(root,relative))})}},async match(request){return store.get(typeof request==='string'?request:request.url)}}},async keys(){return [...stores.keys()]},async delete(name){return stores.delete(name)}};
 const self={registration:{scope},location:new URL(scope),clients:{async claim(){claimed=true}},async skipWaiting(){skipped=true},addEventListener(type,fn){listeners[type]=fn}};
 vm.runInNewContext(fs.readFileSync(path.join(root,'sw.js'),'utf8'),{self,caches,URL,Request,encodeURIComponent,fetch:()=>{network++;return Promise.reject(Error('offline'))},Promise},{filename:'sw.js'});
 const run=async type=>{let pending;listeners[type]({waitUntil(p){pending=p}});await pending};
 return {listeners,stores,caches,run,get status(){return {claimed,skipped,network}},scope};
}
test('every precached asset exists and installs atomically into one scoped cache',async()=>{const e=environment();await e.run('install');assert.equal(e.stores.size,1);assert.equal([...e.stores.values()][0].size,12);assert(e.status.skipped)});
test('offline launch returns cached HTML with zero network requests',async()=>{const e=environment();await e.run('install');let response;e.listeners.fetch({request:{method:'GET',mode:'navigate',url:e.scope},respondWith(p){response=p}});const result=await response;assert.match(result.body.toString(),/Dirhaya/);assert.equal(e.status.network,0)});
test('offline core, UI and style assets resolve from cache',async()=>{const e=environment();await e.run('install');for(const name of ['core.js','storage.js','app.js','styles.css','icons/apple-touch-icon.png']){let response;e.listeners.fetch({request:{method:'GET',mode:'same-origin',url:e.scope+name},respondWith(p){response=p}});assert((await response).body.length>10)}assert.equal(e.status.network,0)});
test('activation deletes only old Dirhaya caches for this deployment scope',async()=>{const e=environment();await e.run('install');const suffix='-'+encodeURIComponent(e.scope);e.stores.set('dirhaya-v0-old'+suffix,new Map());e.stores.set('unrelated-app-v1',new Map());e.stores.set('dirhaya-v0-old-'+encodeURIComponent('https://example.test/other/'),new Map());await e.run('activate');assert.equal(e.stores.size,3);assert(e.stores.has('unrelated-app-v1'));assert(e.status.claimed)});
test('offline-ready message is false when a required asset is missing',async()=>{const e=environment();await e.run('install');let pending,result;const send=()=>{e.listeners.message({data:{type:'OFFLINE_STATUS'},ports:[{postMessage(x){result=x}}],waitUntil(p){pending=p}});return pending};await send();assert.equal(result.ready,true);[...e.stores.values()][0].delete(e.scope+'core.js');await send();assert.equal(result.ready,false)});
test('service worker does not intercept external origins or POST requests',async()=>{const e=environment();let called=false;for(const req of [{method:'GET',mode:'cors',url:'https://third.test/api'},{method:'POST',mode:'same-origin',url:e.scope+'data'},{method:'GET',mode:'navigate',url:'https://example.test/other/'}])e.listeners.fetch({request:req,respondWith(){called=true}});assert.equal(called,false)});
test('manifest supplies standalone display, scoped paths and real icons',()=>{const m=JSON.parse(fs.readFileSync(path.join(root,'manifest.webmanifest')));assert.equal(m.display,'standalone');assert.equal(m.start_url,'./');assert.equal(m.scope,'./');assert.equal(m.name.split(' ')[0],'Dirhaya');for(const i of m.icons)assert(fs.existsSync(path.join(root,i.src)));assert(m.icons.some(i=>i.purpose==='maskable'))});
test('app has local-only executable assets, iPhone metadata and no analytics',()=>{const html=fs.readFileSync(path.join(root,'index.html'),'utf8');assert.match(html,/viewport-fit=cover/);assert.match(html,/apple-touch-icon/);assert.match(html,/apple-mobile-web-app-capable/);for(const match of html.matchAll(/(?:src|href)="([^"]+)"/g)){assert(!/^https?:/.test(match[1]));assert(fs.existsSync(path.join(root,match[1])))}for(const name of ['app.js','core.js','storage.js']){const js=fs.readFileSync(path.join(root,name),'utf8');assert(!/\beval\s*\(|new Function\s*\(/.test(js));assert(!/\bfetch\s*\(|XMLHttpRequest|sendBeacon|WebSocket/.test(js))}});
