const test=require('node:test'),assert=require('node:assert/strict'),C=require('../public/core.js');
const date=C.localDate();
function start(){let s=C.blank();for(const [name,kind] of [['Bank','bank'],['Savings','savings']])s=C.apply(s,{type:'account.add',name,kind,opening:0});return s}
function txn(s,kind,amount,extra={}){return C.apply(s,{type:'transaction.add',kind,amount:amount*100,account:s.accounts[0].id,date,category:kind==='income'?'Salary':'Other',...extra})}
function addGoal(s,name){return C.apply(s,{type:'goal.add',name,target:1000000})}
function scenario(){let s=start();s=txn(s,'income',10000);s=txn(s,'expense',1000);s=addGoal(s,'China trip');s=addGoal(s,'Car');for(const [i,amount] of [[0,200000],[1,150000]])s=C.apply(s,{type:'goal.allocate',id:s.goals[i].id,account:s.accounts[1].id,source:s.accounts[0].id,amount});return C.apply(s,{type:'account.check',id:s.accounts[0].id,balance:100000})}
test('user salary example: AED 4500 is unexplained with AED 3500 saved elsewhere',()=>{const s=scenario(),m=C.summary(s);assert.equal(m.salary,1000000);assert.equal(m.knownSpent,100000);assert.equal(m.unknownSpent,450000);assert.equal(m.spent,550000);assert.equal(m.balances[s.accounts[0].id],100000);assert.equal(m.balances[s.accounts[1].id],350000);assert.equal(m.reserved,350000);assert.equal(m.available,100000);assert.equal(m.total,450000)});
test('explaining AED 500 reduces unknowns without spending or subtracting twice',()=>{let s=scenario();const t=s.transactions.find(t=>t.category==='Unexplained');s=C.apply(s,{type:'transaction.explain',id:t.id,amount:50000,category:'Transport',note:'Forgotten repair'});const m=C.summary(s);assert.equal(m.unknownSpent,400000);assert.equal(m.knownSpent,150000);assert.equal(m.spent,550000);assert.equal(m.total,450000);assert.equal(s.transactions.find(x=>x.id===t.id&&x.category==='Unexplained').amount,400000);s=C.apply(s,{type:'transaction.explain',id:t.id,amount:400000,category:'Other'});assert.equal(C.summary(s).unknownSpent,0);assert.equal(C.summary(s).total,450000);assert(!s.transactions.some(x=>x.id===t.id))});
test('rechecking an unchanged balance adds no further unknown spending',()=>{const s=scenario();const again=C.apply(s,{type:'account.check',id:s.accounts[0].id,balance:100000});assert.equal(again.transactions.length,s.transactions.length);assert.deepEqual(C.summary(again),C.summary(s));assert.equal(again.accounts[0].lastCheck.actual,100000)});
test('new unknown spending only records the difference since the previous check',()=>{let s=scenario();s=txn(s,'expense',100);s=C.apply(s,{type:'account.check',id:s.accounts[0].id,balance:80000});assert.equal(C.summary(s).unknownSpent,460000);assert.equal(C.summary(s).knownSpent,110000);assert.equal(C.summary(s).balances[s.accounts[0].id],80000)});
test('savings within the same account cannot be subtracted from its actual balance again',()=>{let s=txn(start(),'income',10000);s=txn(s,'expense',1000);s=addGoal(s,'Marriage');s=C.apply(s,{type:'goal.allocate',id:s.goals[0].id,account:s.accounts[0].id,amount:350000});assert.equal(C.balances(s)[s.accounts[0].id],900000);assert.throws(()=>C.apply(s,{type:'account.check',id:s.accounts[0].id,balance:100000}),/real account|unfunded/);s=C.apply(s,{type:'goal.release',id:s.goals[0].id,account:s.accounts[0].id,amount:350000});s=C.apply(s,{type:'account.check',id:s.accounts[0].id,balance:100000});assert.equal(C.summary(s).unknownSpent,800000)});
test('linked debit cards add no money; payment subtracts from the bank exactly once',()=>{let s=txn(start(),'income',10000);for(const name of ['Main debit','Second debit'])s=C.apply(s,{type:'card.add',account:s.accounts[0].id,name,last4:'1234'});assert.equal(C.summary(s).total,1000000);s=txn(s,'expense',25,{card:s.cards[0].id});assert.equal(C.summary(s).total,997500);assert.equal(C.summary(s).spent,2500);assert.equal(s.transactions.at(-1).card,s.cards[0].id);assert.throws(()=>C.apply(s,{type:'card.delete',id:s.cards[0].id}));assert.throws(()=>C.apply(s,{type:'card.edit',id:s.cards[0].id,name:'Moved card',account:s.accounts[1].id}));assert.throws(()=>txn(s,'expense',1,{card:s.cards[1].id,account:s.accounts[1].id}));assert.throws(()=>txn(s,'income',1,{card:s.cards[0].id}))});
test('prepaid card holds its own money and cannot be used as linked debit',()=>{let s=start();s=C.apply(s,{type:'account.add',name:'Travel prepaid',kind:'prepaid',opening:50000});assert.equal(C.summary(s).total,50000);assert.throws(()=>C.apply(s,{type:'card.add',name:'Wrong link',account:s.accounts[2].id}));s=txn(s,'expense',50,{account:s.accounts[2].id});assert.equal(C.summary(s).total,45000)});
test('moving goal savings keeps the same saved amount and original saving dates',()=>{let s=scenario();const g=s.goals[0],saved=C.goalSaved(g),day=g.allocations[0].date,total=C.summary(s).total;s=C.apply(s,{type:'goal.move',id:g.id,source:s.accounts[1].id,account:s.accounts[0].id,amount:50000});assert.equal(C.goalSaved(s.goals[0]),saved);assert.equal(C.summary(s).total,total);assert.equal(C.summary(s).reserves[s.accounts[0].id],50000);assert.equal(C.summary(s).balances[s.accounts[0].id],150000);assert(s.goals[0].allocations.every(a=>a.date===day));assert.equal(C.summary(s).spent,550000);assert.throws(()=>C.apply(s,{type:'goal.move',id:g.id,source:s.accounts[0].id,account:s.accounts[1].id,amount:50001}))});
test('unexplained income can be explained as salary without adding money twice',()=>{let s=start();s=C.apply(s,{type:'account.check',id:s.accounts[0].id,balance:100000});let m=C.summary(s);assert.equal(m.unknownIncome,100000);assert.equal(m.salary,0);const id=s.transactions[0].id;s=C.apply(s,{type:'transaction.explain',id,amount:100000,category:'Salary'});m=C.summary(s);assert.equal(m.unknownIncome,0);assert.equal(m.salary,100000);assert.equal(m.total,100000)});
test('categories cannot turn an expense into salary or income into spending',()=>{const s=scenario(),t=s.transactions.find(t=>t.category==='Unexplained');assert.throws(()=>C.apply(s,{type:'transaction.explain',id:t.id,amount:100,category:'Salary'}));assert.throws(()=>txn(s,'expense',1,{category:'Salary'}));assert.throws(()=>txn(s,'income',1,{category:'Travel'}));const bad=C.clone(s);bad.transactions[0].category='Food & drink';assert.throws(()=>C.validate(bad))});
test('card and balance-check metadata survive backup; invalid references fail',()=>{let s=scenario();s=C.apply(s,{type:'card.add',name:'Bank debit',account:s.accounts[0].id,last4:'4321'});assert.deepEqual(C.validate(JSON.parse(JSON.stringify(s))),s);let bad=C.clone(s);bad.cards[0].account='missing';assert.throws(()=>C.validate(bad));bad=C.clone(s);bad.accounts[0].lastCheck.actual=NaN;assert.throws(()=>C.validate(bad));assert.throws(()=>C.apply(s,{type:'account.edit',id:s.accounts[0].id,name:'Bank',kind:'cash'}))});
