const test=require('node:test'),assert=require('node:assert/strict'),C=require('../public/core.js');
function saved(){let s=C.demo();s=C.apply(s,{type:'account.check',id:s.accounts[0].id,balance:C.balances(s)[s.accounts[0].id]-10000});return C.apply(s,{type:'settings',name:'My name',theme:'grey',hideAmounts:true,monthlyBudget:200000,lastBackup:Date.now()})}
test('reset clears financial history and totals but preserves account, card and goal identities',()=>{const original=saved(),snapshot=JSON.stringify(original),s=C.resetMoney(original);assert.equal(s.transactions.length,0);assert.deepEqual(s.accounts.map(a=>[a.id,a.name,a.type,a.color]),original.accounts.map(a=>[a.id,a.name,a.type,a.color]));assert(s.accounts.every(a=>a.opening===0&&!a.lastCheck));assert.deepEqual(s.cards,original.cards);assert.deepEqual(s.goals.map(g=>[g.id,g.name,g.target,g.deadline]),original.goals.map(g=>[g.id,g.name,g.target,g.deadline]));assert(s.goals.every(g=>g.allocations.length===0));const m=C.summary(s);for(const k of ['total','reserved','available','income','spent','salary','unknownSpent','knownSpent','unknownIncome'])assert.equal(m[k],0,k);assert.equal(s.settings.monthlyBudget,0);assert.equal(s.settings.lastBackup,null);assert.equal(JSON.stringify(original),snapshot);assert.doesNotThrow(()=>C.validate(s))});
test('reset retains name, theme and privacy while increasing revision',()=>{const original=saved(),s=C.resetMoney(original);assert.equal(s.settings.name,'My name');assert.equal(s.settings.theme,'grey');assert.equal(s.settings.hideAmounts,true);assert.equal(s.rev,original.rev+1);assert.equal(s.version,original.version)});
test('starting fresh records actual money without manufacturing salary or unexplained income',()=>{let s=C.resetMoney(saved());const a=s.accounts[0];assert(C.canSetOpening(s,a.id));s=C.apply(s,{type:'account.edit',id:a.id,name:a.name,kind:a.type,color:a.color,opening:250000});const m=C.summary(s);assert.equal(m.total,250000);assert.equal(m.salary,0);assert.equal(m.income,0);assert.equal(m.spent,0);assert.equal(m.unknownIncome,0);assert.equal(s.transactions.length,0);assert.equal(C.balances(s)[s.cards[0].account],250000)});
test('new expenses work after setting starting balance and appear only in new history',()=>{let s=C.resetMoney(saved());const a=s.accounts[0];s=C.apply(s,{type:'account.edit',id:a.id,name:a.name,opening:250000});s=C.apply(s,{type:'transaction.add',kind:'expense',account:a.id,card:s.cards[0].id,amount:2500,date:C.localDate(),category:'Food & drink'});assert.equal(C.summary(s).total,247500);assert.equal(C.summary(s).spent,2500);assert.equal(s.transactions.length,1);assert(!C.canSetOpening(s,a.id));assert.throws(()=>C.apply(s,{type:'account.edit',id:a.id,name:a.name,opening:500000}),/already has activity/)});
test('incoming transfers and saved goals also protect the historical starting balance',()=>{let s=C.resetMoney(saved());const [a,b]=s.accounts;s=C.apply(s,{type:'account.edit',id:a.id,name:a.name,opening:100000});s=C.apply(s,{type:'transaction.add',kind:'transfer',account:a.id,to:b.id,amount:50000,date:C.localDate()});assert(!C.canSetOpening(s,b.id));assert.throws(()=>C.apply(s,{type:'account.edit',id:b.id,name:b.name,opening:1}));s=C.resetMoney(s);s=C.apply(s,{type:'account.edit',id:a.id,name:a.name,opening:100000});s=C.apply(s,{type:'goal.allocate',id:s.goals[0].id,account:a.id,amount:10000});assert(!C.canSetOpening(s,a.id));assert.throws(()=>C.apply(s,{type:'account.edit',id:a.id,name:a.name,opening:10001}))});
test('normal account edits with unchanged opening still work for accounts with history',()=>{const original=saved(),a=original.accounts[0];const s=C.apply(original,{type:'account.edit',id:a.id,name:'New name',opening:a.opening});assert.equal(s.accounts[0].name,'New name');assert.deepEqual(C.balances(s),C.balances(original))});
test('invalid starting balances do not mutate the reset records',()=>{const s=C.resetMoney(saved()),a=s.accounts[0],snapshot=JSON.stringify(s);for(const opening of [-1,NaN,1.5])assert.throws(()=>C.apply(s,{type:'account.edit',id:a.id,name:a.name,opening}));assert.equal(JSON.stringify(s),snapshot);assert.equal(C.canSetOpening(s,'missing'),false)});
