const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),{webcrypto,createPrivateKey,sign}=require('node:crypto');
async function fixture(){const store=new Map(),location={origin:'https://example.test',hostname:'example.test',pathname:'/money/'},pair=await webcrypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']),publicKey=await webcrypto.subtle.exportKey('spki',pair.publicKey),privateKey=createPrivateKey({key:Buffer.from(await webcrypto.subtle.exportKey('pkcs8',pair.privateKey)),type:'pkcs8',format:'der'}),rawId=new Uint8Array([1,2,3,4]);let tamper='',cancel=false;
 const response=async(challenge,type)=>{const client=Buffer.from(JSON.stringify({type,challenge:Buffer.from(challenge).toString('base64url'),origin:tamper==='origin'?'https://wrong.test':location.origin,crossOrigin:false})),auth=Buffer.alloc(37);Buffer.from(await webcrypto.subtle.digest('SHA-256',Buffer.from(location.hostname))).copy(auth);auth[32]=tamper==='verification'?1:5;if(tamper==='rp')auth[0]^=1;const signed=Buffer.concat([auth,Buffer.from(await webcrypto.subtle.digest('SHA-256',client))]),signature=sign('sha256',signed,privateKey);if(tamper==='signature')signature[signature.length-1]^=1;return {clientDataJSON:client,authenticatorData:auth,signature,getAuthenticatorData:()=>auth,getPublicKeyAlgorithm:()=>-7,getPublicKey:()=>publicKey}};
 const navigator={credentials:{async create({publicKey:o}){if(cancel)throw Error('cancelled');assert.equal(o.authenticatorSelection.userVerification,'required');return {type:'public-key',rawId,response:await response(o.challenge,'webauthn.create')}},async get({publicKey:o}){if(cancel)throw Error('cancelled');assert.equal(o.userVerification,'required');const c=tamper==='challenge'?new Uint8Array(32):o.challenge;return {type:'public-key',rawId:tamper==='id'?new Uint8Array([5]):rawId,response:await response(c,'webauthn.get')}}}};
 const ctx={location,crypto:webcrypto,navigator,isSecureContext:true,PublicKeyCredential:{isUserVerifyingPlatformAuthenticatorAvailable:async()=>true},localStorage:{getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)},TextEncoder,TextDecoder,Uint8Array,btoa:x=>Buffer.from(x,'binary').toString('base64'),atob:x=>Buffer.from(x,'base64').toString('binary')};vm.runInNewContext(fs.readFileSync(require.resolve('../public/security.js'),'utf8'),ctx);return {api:ctx.DirhayaSecurity,store,setTamper:t=>tamper=t,setCancel:x=>cancel=x};}
test('passkey setup verifies real signatures and stays disabled until activation',async()=>{const e=await fixture(),code=await e.api.prepare();assert.match(code,/^[A-F0-9]{4}(?:-[A-F0-9]{4}){7}$/);assert.equal(e.api.enabled(),false);e.api.activate();assert.equal(e.api.enabled(),true);assert.equal(await e.api.authenticate(),true);assert(![...e.store.values()][0].includes(code.replace(/-/g,'')))});
test('assertions reject wrong origins, challenges, credential IDs, RP hashes, signatures and absent verification',async()=>{const e=await fixture();await e.api.prepare();e.api.activate();for(const kind of ['origin','challenge','id','rp','signature','verification']){e.setTamper(kind);await assert.rejects(()=>e.api.authenticate());assert.equal(e.api.enabled(),true)}});
test('cancelled authentication keeps the lock enabled; recovery rejects incorrect codes',async()=>{const e=await fixture(),code=await e.api.prepare();e.api.activate();e.setCancel(true);await assert.rejects(()=>e.api.disable());assert.equal(e.api.enabled(),true);await assert.rejects(()=>e.api.recover('0000'));assert.equal(e.api.enabled(),true);await e.api.recover(code);assert.equal(e.api.enabled(),false)});
test('cancelled or invalid setup never enables a lock',async()=>{const e=await fixture();e.setCancel(true);await assert.rejects(()=>e.api.prepare());assert.equal(e.api.enabled(),false);assert.throws(()=>e.api.activate());e.setCancel(false);e.setTamper('signature');await assert.rejects(()=>e.api.prepare());assert.throws(()=>e.api.activate())});
test('disabling requires a verified assertion and corrupt config stays fail-closed',async()=>{const e=await fixture();await e.api.prepare();e.api.activate();await e.api.disable();assert.equal(e.api.enabled(),false);e.store.set('dirhaya-screen-lock:/money/','{broken');assert.equal(e.api.enabled(),true);await assert.rejects(()=>e.api.authenticate())});
