/* Tests production storage logic against a transaction-serialising memory adapter.
   Real Safari IndexedDB still requires the browser tests. */
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const C=require('../public/core.js');
function fakeDB(){
 let data=new Map(),queue=[],busy=false,failNext=false;
 function startNext(){if(busy||!queue.length)return;busy=true;const tx=queue.shift();tx._start()}
 const db={createObjectStore(){},close(){},transaction(name,mode){let pending=0,started=false,ended=false,ops=[],snapshot,error;const tx={objectStore(){return {clear(){return request(()=>snapshot.clear())},get(id){return request(()=>snapshot.get(id))},put(value){if(failNext){failNext=false;throw Error('Simulated quota error')}return request(()=>{snapshot.set(value.id,structuredClone(value));return value.id})}}},abort(){if(ended)return;ended=true;error=Error('Aborted');setImmediate(()=>{tx.onabort?.();busy=false;startNext()})},_start(){started=true;snapshot=new Map([...data].map(([k,v])=>[k,structuredClone(v)]));ops.splice(0).forEach(execute);scheduleFinish()}};
 function scheduleFinish(){setImmediate(()=>{if(ended||pending)return;ended=true;if(mode==='readwrite')data=snapshot;tx.oncomplete?.();busy=false;startNext()})}
 function execute(job){setImmediate(()=>{if(ended)return;try{job.req.result=structuredClone(job.fn());job.req.onsuccess?.()}catch(e){tx.error=e;job.req.onerror?.();tx.abort()}pending--;scheduleFinish()})}
 function request(fn){const req={};pending++;const job={req,fn};if(started)execute(job);else ops.push(job);return req}
 queue.push(tx);setImmediate(startNext);return tx}};
 return {indexedDB:{open(){const req={};setImmediate(()=>{req.result=db;req.onupgradeneeded?.();req.onsuccess?.()});return req}},fail(){failNext=true},snapshot(){return structuredClone(data)}};
}
function env(adapter=fakeDB()){const context={DirhayaCore:C,indexedDB:adapter.indexedDB,BroadcastChannel:class{postMessage(){}},CustomEvent:class{},dispatchEvent(){},Promise,Error,globalThis:null};context.globalThis=context;vm.runInNewContext(fs.readFileSync(require.resolve('../public/storage.js'),'utf8'),context);return {S:context.DirhayaStorage,adapter}}

test('initial data persists and is read again on a fresh app instance',async()=>{const {S,adapter}=env();await S.init();await S.mutate({type:'account.add',name:'Bank',kind:'bank',opening:10000,color:'sand'});const second=env(adapter).S;const reopened=await second.init();assert.equal(reopened.accounts[0].name,'Bank');assert.equal(C.summary(reopened).total,10000)});
test('concurrent local mutations read the latest committed state',async()=>{const {S}=env();await S.init();let s=await S.mutate({type:'account.add',name:'Cash',kind:'cash',opening:0,color:'sand'});const id=s.accounts[0].id;await Promise.all(Array.from({length:40},()=>S.mutate({type:'transaction.add',kind:'income',amount:1,account:id,date:C.localDate(),category:'Other income',note:''})));s=await S.get();assert.equal(s.transactions.length,40);assert.equal(C.summary(s).total,40);assert.equal(s.rev,41)});
test('validation failure aborts the complete transaction',async()=>{const {S}=env();await S.init();let s=await S.mutate({type:'account.add',name:'Cash',kind:'cash',opening:100,color:'sand'});const before=JSON.stringify(s);await assert.rejects(S.mutate({type:'transaction.add',kind:'expense',amount:101,account:s.accounts[0].id,date:C.localDate(),note:'',category:'Other'}));assert.equal(JSON.stringify(await S.get()),before)});
test('quota failure does not publish partial or optimistic data',async()=>{const {S,adapter}=env();await S.init();const before=JSON.stringify(await S.get());adapter.fail();await assert.rejects(S.mutate({type:'account.add',name:'Failed',kind:'bank',opening:100,color:'sand'}));assert.equal(JSON.stringify(await S.get()),before);await S.mutate({type:'account.add',name:'Retry',kind:'bank',opening:100,color:'sand'});assert.equal((await S.get()).accounts[0].name,'Retry')});
test('restore keeps a recoverable prior snapshot and fresh revision',async()=>{const {S}=env();await S.init();let original=await S.mutate({type:'account.add',name:'My money',kind:'bank',opening:12345,color:'sand'});const demo=C.demo();let restored=await S.restore(demo);assert.equal(restored.rev,original.rev+1);assert.equal(restored.accounts.length,3);const recovered=await S.recover();assert.equal(recovered.accounts[0].name,'My money');assert.equal(C.summary(recovered).total,12345);assert.equal(recovered.rev,restored.rev+1)});
test('invalid restore data cannot replace device records',async()=>{const {S}=env();await S.init();const before=JSON.stringify(await S.get());assert.throws(()=>S.restore({format:'wrong'}));assert.equal(JSON.stringify(await S.get()),before);await assert.rejects(S.recover(),/No earlier restore/) });

test('splits commit atomically, survive reopening and roll back both portions on storage failure',async()=>{
 const {S,adapter}=env();await S.init();let s=await S.mutate({type:'account.add',name:'Bank',kind:'bank',opening:1000000});
 s=await S.mutate({type:'transaction.add',kind:'expense',amount:450000,account:s.accounts[0].id,date:C.localDate(),category:'Unexplained'});
 const snapshot=JSON.stringify(s),id=s.transactions[0].id,date=C.localDate(new Date(new Date().getFullYear(),new Date().getMonth()-1,15));adapter.fail();
 await assert.rejects(S.mutate({type:'transaction.split',id,amount:150000,date}));assert.equal(JSON.stringify(await S.get()),snapshot);
 await S.mutate({type:'transaction.split',id,amount:150000,date});const restored=await env(adapter).S.init();assert.equal(C.summary(restored).spent,300000);assert.equal(C.summary(restored,date).spent,150000);assert.equal(C.summary(restored).total,550000);assert.equal(restored.transactions.length,2);
});

test('reset preserves account setup across reopening and removes the old restore snapshot',async()=>{
 const {S,adapter}=env();await S.init();await S.restore(C.demo());const before=await S.get();assert(adapter.snapshot().has('before-restore'));
 const reset=await S.resetMoney();assert.equal(reset.rev,before.rev+1);assert.deepEqual(reset.accounts.map(a=>a.id),before.accounts.map(a=>a.id));assert.deepEqual(reset.cards,before.cards);assert.equal(reset.transactions.length,0);assert.equal(C.summary(reset).total,0);assert.equal(adapter.snapshot().size,1);assert(!adapter.snapshot().has('before-restore'));
 const reopened=await env(adapter).S.init();assert.deepEqual(reopened,reset);await assert.rejects(S.recover(),/No earlier restore/);
});
test('failed reset rolls back both the financial records and the recovery snapshot',async()=>{
 const {S,adapter}=env();await S.init();await S.restore(C.demo());const records=JSON.stringify(await S.get()),snapshot=adapter.snapshot();adapter.fail();await assert.rejects(S.resetMoney());assert.equal(JSON.stringify(await S.get()),records);assert.deepEqual(adapter.snapshot(),snapshot);
});
test('an exported pre-reset backup can still restore all earlier records',async()=>{
 const {S}=env();await S.init();await S.restore(C.demo());const backup=JSON.parse(JSON.stringify(await S.get()));await S.resetMoney();assert.equal(C.summary(await S.get()).total,0);const restored=await S.restore(backup);assert.equal(C.summary(restored).total,C.summary(backup).total);assert.deepEqual(restored.transactions,backup.transactions);assert.deepEqual(restored.goals,backup.goals);
});

test('start from today snapshot is atomic, preserves existing records across reload, and can be undone',async()=>{const {S,adapter}=env();await S.init();const old=C.clone(await S.restore(C.demo())),action={type:'tracking.start',expectedRev:old.rev,balances:old.accounts.map(a=>({id:a.id,balance:C.balances(old)[a.id]}))};adapter.fail();await assert.rejects(S.mutate(action));assert.deepEqual(await S.get(),old);assert(!adapter.snapshot().has('before-start'));const next=await S.mutate(action);assert.equal(C.summary(next).spent,0);const reopened=env(adapter).S;assert.deepEqual(await reopened.init(),next);const recovered=await reopened.undoStart();assert.deepEqual(recovered.transactions,old.transactions);assert.deepEqual(C.balances(recovered),C.balances(old));assert(adapter.snapshot().has('before-restore'))});
test('two concurrent recurring confirmations commit a single occurrence and preserve every other entry',async()=>{const {S}=env();await S.init();let s=await S.restore(C.demo());s=await S.mutate({type:'recurring.save',name:'Subscription',kind:'expense',category:'Bills',amount:1000,account:s.accounts[0].id,frequency:'monthly',nextDate:C.localDate()});const r=s.recurring[0],action={type:'recurring.record',id:r.id,dueDate:r.nextDate,account:r.account,amount:r.amount,date:C.localDate()},results=await Promise.allSettled([S.mutate(action),S.mutate(action)]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal(results.filter(x=>x.status==='rejected').length,1);const final=await S.get();assert.equal(final.transactions.length,s.transactions.length+1);assert.equal(final.transactions.filter(t=>t.recurringId===r.id).length,1)});
test('failed recurring commit keeps occurrence pending and no transaction is partially saved',async()=>{const {S,adapter}=env();await S.init();let s=await S.restore(C.demo());s=await S.mutate({type:'recurring.save',name:'Salary',kind:'income',category:'Salary',amount:100000,account:s.accounts[0].id,frequency:'monthly',nextDate:C.localDate()});const r=s.recurring[0];adapter.fail();await assert.rejects(S.mutate({type:'recurring.record',id:r.id,dueDate:r.nextDate,account:r.account,amount:r.amount,date:r.nextDate}));assert.deepEqual(await S.get(),s)});
test('restore refuses stale review after another window saves an entry',async()=>{const {S}=env();await S.init();const old=await S.restore(C.demo());const current=await S.mutate({type:'transaction.add',kind:'expense',amount:100,account:old.accounts[0].id,date:C.localDate(),category:'Laundry'});await assert.rejects(S.restore(C.blank(),old.rev),/records changed/);assert.deepEqual(await S.get(),current)});
test('actual 1.8 synthetic records reopen unchanged under 1.9 before any user action',async()=>{const legacy=require('./fixtures/v1.8-synthetic.json'),{S,adapter}=env();await S.init();await S.restore(legacy);const before=C.clone(await S.get());const reopened=await env(adapter).S.init();assert.deepEqual(reopened,before);assert.deepEqual(reopened.accounts,legacy.accounts);assert.deepEqual(reopened.cards,legacy.cards);assert.deepEqual(reopened.transactions,legacy.transactions);assert.deepEqual(reopened.goals,legacy.goals);assert.deepEqual(reopened.settings,legacy.settings);assert.equal(C.summary(reopened).total,C.summary(legacy).total);const B=require('../public/backups.js'),exported=await B.create(reopened,{password:'synthetic upgrade passphrase'}),decoded=await B.decode(exported.text,'synthetic upgrade passphrase');assert.deepEqual(decoded.accounts,legacy.accounts);assert.deepEqual(decoded.transactions,legacy.transactions);assert.deepEqual(decoded.goals,legacy.goals)});
