const test=require('node:test'),assert=require('node:assert/strict'),C=require('../public/core.js');
function seed(){let s=C.blank();for(const [name,kind,opening] of [['Main','bank',100000],['Cash','cash',30000],['Portfolio','investment',50000]])s=C.apply(s,{type:'account.add',name,kind,opening});return s}
function schedule(s,extra={}){return C.apply(s,{type:'recurring.save',name:'Rent',kind:'expense',category:'Bills',account:s.accounts[0].id,amount:10000,frequency:'monthly',nextDate:'2026-01-31',...extra})}
function start(s,changes={}){return C.apply(s,{type:'tracking.start',expectedRev:s.rev,balances:s.accounts.map(a=>({id:a.id,balance:changes[a.name]??C.balances(s)[a.id]}))})}
test('overview partitions total and investment-backed goals without counting linked cards or holdings twice',()=>{let s=seed();s=C.apply(s,{type:'card.add',name:'Debit',account:s.accounts[0].id});s=C.apply(s,{type:'holding.add',account:s.accounts[2].id,name:'Example',quantity:'4',cost:40000,value:40000,mode:'included'});s=C.apply(s,{type:'goal.add',name:'Goal',target:80000});const g=s.goals[0].id;s=C.apply(s,{type:'goal.allocate',id:g,account:s.accounts[0].id,amount:20000});s=C.apply(s,{type:'goal.allocate',id:g,account:s.accounts[2].id,amount:30000});const m=C.summary(s);assert.equal(m.total,180000);assert.equal(m.availableCash,110000);assert.equal(m.cashGoals,20000);assert.equal(m.investmentTotal,50000);assert.equal(m.holdings,40000);assert.equal(m.portfolioUnassigned,10000);assert.equal(m.investmentGoals,30000);assert.equal(m.availableCash+m.cashGoals+m.investmentTotal,m.total);assert.equal(m.cashGoals+m.investmentGoals,m.reserved)});
test('start today preserves identifiers and history, corrects balances, and excludes pre-setup entries even from today',()=>{let s=seed();s=C.apply(s,{type:'transaction.add',kind:'income',amount:90000,account:s.accounts[0].id,date:C.localDate(),category:'Salary'});s=C.apply(s,{type:'transaction.add',kind:'expense',amount:20000,account:s.accounts[0].id,date:C.localDate(),category:'Food & drink'});const old=C.clone(s),fresh=start(s,{Main:120000});assert.deepEqual(fresh.accounts,old.accounts);assert.deepEqual(s,old);assert.equal(fresh.transactions.length,3);assert.equal(fresh.transactions[0].id,old.transactions[0].id);assert.equal(fresh.transactions.at(-1).type,'adjustment');assert.equal(C.balances(fresh)[s.accounts[0].id],120000);assert.equal(C.summary(fresh).income,0);assert.equal(C.summary(fresh).spent,0);assert.equal(C.summary(fresh,C.localDate(),{allHistory:true}).spent,20000);const next=C.apply(fresh,{type:'transaction.add',kind:'expense',amount:1234,account:s.accounts[0].id,date:C.localDate(),category:'Laundry'});assert.equal(C.summary(next).spent,1234);assert.equal(C.balances(next)[s.accounts[0].id],118766);const showAll=C.apply(next,{type:'tracking.show-all'});assert.equal(C.summary(showAll).spent,21234);assert.deepEqual(C.balances(showAll),C.balances(next))});
test('editing or splitting pre-setup transactions preserves their tracking exclusion',()=>{let s=seed();s=C.apply(s,{type:'transaction.add',kind:'expense',amount:1000,account:s.accounts[0].id,date:C.localDate(),category:'Other'});s=start(s);const t=s.transactions[0];s=C.apply(s,{type:'transaction.edit',id:t.id,kind:'expense',amount:1000,account:t.account,date:t.date,category:'Laundry'});s=C.apply(s,{type:'transaction.split',id:t.id,amount:400,date:t.date});assert.equal(C.summary(s).spent,0);assert.equal(C.summary(s,t.date,{allHistory:true}).spent,1000)});
test('setup rejects stale, partial and duplicated account balances atomically',()=>{const s=seed(),before=JSON.stringify(s),rows=s.accounts.map(a=>({id:a.id,balance:a.opening}));for(const action of [{expectedRev:s.rev-1,balances:rows},{expectedRev:s.rev,balances:rows.slice(1)},{expectedRev:s.rev,balances:[rows[0],rows[0],rows[2]]}])assert.throws(()=>C.apply(s,{type:'tracking.start',...action}));assert.equal(JSON.stringify(s),before)});
test('setup cannot erase invested value or silently remove unfunded goal allocations',()=>{let s=seed();s=C.apply(s,{type:'holding.add',account:s.accounts[2].id,name:'Example',quantity:'4',cost:40000,value:40000,mode:'included'});assert.throws(()=>start(s,{Portfolio:30000}),/investments/);s=C.apply(s,{type:'goal.add',name:'Goal',target:50000});s=C.apply(s,{type:'goal.allocate',id:s.goals[0].id,account:s.accounts[0].id,amount:50000});assert.throws(()=>start(s,{Main:1000}),/reserved/)});
test('recurring schedules and due queries do not move money or create transactions',()=>{const s=seed(),scheduled=schedule(s),before=JSON.stringify(scheduled);assert.equal(C.dueRecurring(scheduled,'2026-01-30').length,0);assert.equal(C.dueRecurring(scheduled,'2026-02-01').length,1);assert.equal(scheduled.transactions.length,0);assert.deepEqual(C.balances(scheduled),C.balances(s));assert.equal(JSON.stringify(scheduled),before)});
test('recurring confirmation records reviewed values once and preserves month-end anchor',()=>{let s=schedule(seed());const r=s.recurring[0],action={type:'recurring.record',id:r.id,dueDate:r.nextDate,amount:12500,account:s.accounts[1].id,date:'2026-02-01',note:'Actual rent'};s=C.apply(s,action);const t=s.transactions[0];assert.equal(t.amount,12500);assert.equal(t.account,s.accounts[1].id);assert.equal(t.date,'2026-02-01');assert.equal(t.recurringId,r.id);assert.equal(s.recurring[0].nextDate,'2026-02-28');assert.equal(s.recurring[0].amount,10000);assert.throws(()=>C.apply(s,action),/no longer/);s=C.apply(s,{type:'recurring.skip',id:r.id,dueDate:'2026-02-28'});assert.equal(s.recurring[0].nextDate,'2026-03-31');assert.equal(s.transactions.length,1)});
test('deleting a confirmed transaction never reopens its scheduled occurrence',()=>{let s=schedule(seed());const r=s.recurring[0],action={type:'recurring.record',id:r.id,dueDate:r.nextDate,amount:10000,account:r.account,date:r.nextDate};s=C.apply(s,action);s=C.apply(s,{type:'transaction.delete',id:s.transactions[0].id});assert.throws(()=>C.apply(s,action),/no longer/);assert.throws(()=>C.apply(s,{type:'recurring.save',...r,expectedNext:s.recurring[0].nextDate}),/already recorded/)});
test('invalid recurring confirmation leaves the occurrence pending without changing balances',()=>{const s=schedule(seed()),r=s.recurring[0],before=JSON.stringify(s);assert.throws(()=>C.apply(s,{type:'recurring.record',id:r.id,dueDate:r.nextDate,amount:999999,account:r.account,date:r.nextDate}),/negative balance/);assert.equal(JSON.stringify(s),before);assert.equal(C.dueRecurring(s).length,1)});
test('pause, future due dates, wrong account and bad imports are rejected or kept out of the review queue',()=>{let s=schedule(seed(),{paused:true});assert.equal(C.dueRecurring(s).length,0);assert.throws(()=>C.apply(s,{type:'recurring.skip',id:s.recurring[0].id,dueDate:s.recurring[0].nextDate}));assert.throws(()=>schedule(seed(),{account:'missing'}));assert.throws(()=>schedule(seed(),{kind:'income',category:'Laundry'}));s=schedule(seed(),{nextDate:'2090-01-01'});assert.equal(C.dueRecurring(s).length,0);s.recurring[0].handled=['bad'];assert.throws(()=>C.validate(s))});
test('day, week, monthly leap and yearly leap recurrence dates use local calendar days',()=>{for(const [date,frequency,anchorDay,anchorMonth,expected] of [['2026-12-31','daily',31,12,'2027-01-01'],['2026-12-29','weekly',29,12,'2027-01-05'],['2028-01-31','monthly',31,1,'2028-02-29'],['2028-02-29','yearly',29,2,'2029-02-28'],['2031-02-28','yearly',29,2,'2032-02-29']])assert.equal(C.nextOccurrence({nextDate:date,frequency,anchorDay,anchorMonth}),expected)});
test('quick category and default payment preferences validate and survive existing backup format',()=>{let s=seed();s=C.apply(s,{type:'settings',quickCategories:['Laundry','Food & drink'],defaultPayment:s.accounts[1].id});assert.deepEqual(C.quickCategories(s),['Laundry','Food & drink']);assert.doesNotThrow(()=>C.validate(JSON.parse(JSON.stringify(s))));for(const categories of [['Salary'],['Laundry','Laundry'],['Unexplained']])assert.throws(()=>C.apply(s,{type:'settings',quickCategories:categories}));assert.throws(()=>C.apply(s,{type:'settings',defaultPayment:'missing'}));assert.deepEqual(C.quickCategories(C.blank()),C.DEFAULT_QUICK)});
test('legacy records upgrade without a schema rewrite or financial changes',()=>{const legacy=C.demo(),before=JSON.stringify(legacy);assert.doesNotThrow(()=>C.validate(legacy));C.summary(legacy);C.dueRecurring(legacy);C.quickCategories(legacy);assert.equal(JSON.stringify(legacy),before);const updated=C.apply(legacy,{type:'settings',quickCategories:['Laundry']});assert.deepEqual(updated.accounts,legacy.accounts);assert.deepEqual(updated.transactions,legacy.transactions);assert.deepEqual(updated.goals,legacy.goals);assert.equal(updated.version,legacy.version)});
