/* Template/interaction smoke tests with a minimal DOM adapter, not a visual browser. */
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');const C=require('../public/core.js');
function environment(seed=C.demo(),preview=false){
 const elements=new Map();function el(id){if(elements.has(id))return elements.get(id);const o={innerHTML:'',textContent:'',content:'',value:'',style:{setProperty(){}},dataset:{},open:false,disabled:false,scrollHeight:100,scrollTop:0,classList:{toggle(){},add(){},remove(){}},addEventListener(){},querySelector(s){return el(s)},querySelectorAll(){return []},append(){},remove(){},click(){},focus(){},showModal(){this.open=true},close(){this.open=false},getBoundingClientRect(){return {left:0,top:0,right:100,bottom:100}},scrollIntoView(){}};elements.set(id,o);return o}
 const document={querySelector:el,querySelectorAll(){return []},createElement:n=>el('new-'+n),addEventListener(){},body:el('body'),documentElement:el('html')};let stored=C.clone(seed),writes=0;
 const storage={async init(){return C.clone(stored)},async get(){return C.clone(stored)},async mutate(action){writes++;stored=C.apply(stored,action);return C.clone(stored)}};
 const ctx={DIRHAYA_PREVIEW:preview,DirhayaCore:C,DirhayaStorage:storage,document,console,window:null,navigator:{},location:{protocol:'file:'},innerWidth:440,innerHeight:956,matchMedia:()=>({matches:false}),setTimeout:()=>1,clearTimeout(){},FormData:class{constructor(form){this.values=form.values||{}}get(key){return this.values[key]??null}},Date,Math,Promise,URL,File:class{},Blob,addEventListener(){},scrollTo(){},isSecureContext:false};ctx.window=ctx;
 let src=fs.readFileSync(require.resolve('../public/app.js'),'utf8');src=src.replace(/init\(\);\s*\}\)\(\);\s*$/,`window.UI={init,render,dispatch,transactionForm,goalForm,accountForm,allocateForm,installSheet,sendMessage,homeView,accountsView,goalsView,activityView,settingsView,chatView,get state(){return state},setState(s){state=s;realState=s},get messages(){return messages}};})();`);vm.runInNewContext(src,ctx);ctx.UI.setState(C.clone(seed));return {ui:ctx.UI,el,elements,get writes(){return writes},get stored(){return stored}};
}
test('all main views render from actual valid data without template exceptions',async()=>{const e=environment();for(const view of ['home','accounts','goals','activity','assistant']){await e.ui.dispatch('view:'+view);assert(e.el('#app').innerHTML.includes('dirhaya'));assert(!e.el('#app').innerHTML.includes('NaN'))}await e.ui.dispatch('settings');assert.match(e.el('#app').innerHTML,/Yours, on this device/)});
test('account and goal names are HTML escaped',()=>{const s=C.demo();s.accounts[0].name='<img src=x onerror=alert(1)>';s.goals[0].name='<script>bad</script>';const e=environment(s);assert.match(e.ui.accountsView(),/&lt;img/);assert(!e.ui.accountsView().includes('<img src=x'));assert.match(e.ui.goalsView(),/&lt;script&gt;/)});
test('demo mutations never overwrite actual saved records',async()=>{const s=C.blank(),e=environment(s);await e.ui.dispatch('demo');assert.equal(e.ui.state.accounts.length,3);await e.ui.dispatch('privacy');assert.equal(e.writes,0);assert.equal(e.stored.accounts.length,0);await e.ui.dispatch('exit-demo');assert.equal(e.ui.state.accounts.length,0)});
test('privacy toggle hides account values and removes prior chat messages',async()=>{const e=environment();await e.ui.dispatch('view:assistant');e.ui.sendMessage('balance');assert(e.ui.messages.length>0);await e.ui.dispatch('privacy');assert.equal(e.ui.messages.length,0);assert.match(e.ui.homeView(),/••••/);assert(!e.ui.accountsView().includes('8,302.00'))});
test('entry form defaults transfers to a different account',()=>{const e=environment();e.ui.transactionForm({kind:'transfer'});const html=e.el('#sheet').innerHTML,source=e.ui.state.accounts[0].id,destination=e.ui.state.accounts[1].id;const destinationSection=html.split('<select name="to"')[1].split('</select>')[0];assert(destinationSection.includes(`value="${destination}" selected`));assert(!destinationSection.includes(`value="${source}" selected`))});
test('all primary entry forms and detail sheets build correctly',async()=>{const e=environment();e.ui.accountForm();assert.match(e.el('#sheet').innerHTML,/Current balance/);e.ui.goalForm();assert.match(e.el('#sheet').innerHTML,/Target date/);e.ui.allocateForm(e.ui.state.goals[0].id);assert.match(e.el('#sheet').innerHTML,/Where the savings will be held/);assert.match(e.el('#sheet').innerHTML,/Take the money from/);await e.ui.dispatch('account:'+e.ui.state.accounts[0].id);assert.match(e.el('#sheet').innerHTML,/Check actual balance/);e.ui.installSheet();assert.match(e.el('#sheet').innerHTML,/preview/)});
test('separate cards, linked payments, and goal presets render',async()=>{let s=C.demo();s=C.apply(s,{type:'card.add',account:s.accounts[0].id,name:'Second debit',last4:'5678'});const e=environment(s);assert.match(e.ui.accountsView(),/Debit cards/);await e.ui.dispatch('card:'+s.cards[0].id);assert.match(e.el('#sheet').innerHTML,/counted once/);await e.ui.dispatch('card-entry:'+s.cards[0].id);assert.match(e.el('#sheet').innerHTML,new RegExp(`value="card:${s.cards[0].id}" selected`));await e.ui.dispatch('add-card');assert.match(e.el('#sheet').innerHTML,/Last four digits/);for(const key of ['china','car','marriage']){await e.ui.dispatch('goal-template:'+key);assert.match(e.el('#sheet').innerHTML,/value="(?:China trip|Car|Marriage)"/)}await e.ui.dispatch('move-goal:'+s.goals[0].id);assert.match(e.el('#sheet').innerHTML,/Record savings move/)});
test('balance check previews the gap and offers partial explanations',async()=>{let s=C.demo();const aid=s.accounts[0].id;s=C.apply(s,{type:'account.check',id:aid,balance:C.balances(s)[aid]-10000});const e=environment(s),unknown=s.transactions.find(t=>t.category==='Unexplained');await e.ui.dispatch('reconcile:'+aid);e.el('#actual-balance').oninput({target:{value:String((C.balances(s)[aid]-5000)/100)}});assert.match(e.el('#gap-preview').innerHTML,/50.00 unexplained spending/);await e.ui.dispatch('explain:'+unknown.id);assert.match(e.el('#sheet').innerHTML,/does not subtract it from your account again/);await e.ui.dispatch('unexplained');assert.match(e.el('#activity-results').innerHTML,/1 entry/);assert.match(e.ui.homeView(),/Known spending this month/)});

test('interactive preview labels its sample data and never saves mutations',async()=>{const e=environment(C.blank(),true);await e.ui.init();assert.match(e.el('#app').innerHTML,/Interactive preview · sample money · changes are not saved/);assert.match(e.el('#app').innerHTML,/Preview · not saved/);await e.ui.dispatch('privacy');assert.equal(e.writes,0);assert.equal(e.stored.accounts.length,0)});

test('split sheet previews and saves a date split through the actual form handler',async()=>{
 const e=environment(),t=e.ui.state.transactions.find(t=>t.type==='expense'),date=C.localDate(new Date(new Date().getFullYear(),new Date().getMonth()-1,15));
 const before=C.balances(e.ui.state);await e.ui.dispatch('transaction:'+t.id);assert.match(e.el('#sheet').innerHTML,/Split across months/);
 await e.ui.dispatch('split-transaction:'+t.id);assert.match(e.el('#sheet').innerHTML,/Date for this portion/);
 e.el('#split-amount').value='10';e.el('#split-date').value=date;e.el('#split-amount').oninput();assert.match(e.el('#split-preview').textContent,/10.00/);
 e.el('#split-form').values={amount:'10',date};await e.el('#split-form').onsubmit({preventDefault(){}});
 assert.equal(e.writes,1);assert.deepEqual(C.balances(e.ui.state),before);assert.equal(e.ui.state.transactions.find(x=>x.splitFrom===t.id).date,date);assert.equal(C.summary(e.ui.state,date).spent,1000);
});
test('explaining a portion exposes and submits the spending date',async()=>{
 let s=C.demo();s=C.apply(s,{type:'account.check',id:s.accounts[0].id,balance:C.balances(s)[s.accounts[0].id]-10000});const t=s.transactions.find(x=>x.category==='Unexplained'),e=environment(s),date=C.localDate(new Date(new Date().getFullYear(),new Date().getMonth()-1,15));
 await e.ui.dispatch('explain:'+t.id);assert.match(e.el('#sheet').innerHTML,/When did this happen/);assert.match(e.el('#sheet').innerHTML,new RegExp('value="'+t.date+'"'));
 e.el('#explain-form').values={amount:'25',category:'Transport',date,note:'Last month'};await e.el('#explain-form').onsubmit({preventDefault(){}});
 assert.equal(C.summary(e.ui.state,date).knownSpent,2500);assert.deepEqual(C.balances(e.ui.state),C.balances(s));
});
