/* Template/interaction smoke tests with a minimal DOM adapter, not a visual browser. */
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');const C=require('../public/core.js');
function environment(seed=C.demo(),preview=false){
 const elements=new Map();function el(id){if(elements.has(id))return elements.get(id);const o={innerHTML:'',textContent:'',content:'',value:'',style:{setProperty(){}},dataset:{},open:false,disabled:false,scrollHeight:100,scrollTop:0,classList:{toggle(){},add(){},remove(){}},addEventListener(){},querySelector(s){return el(s)},querySelectorAll(){return []},append(){},prepend(child){child.parentNode=this},dispatchEvent(){},remove(){},click(){},focus(){},modalShows:0,showModal(){this.open=true;this.modalShows++},close(){this.open=false},getBoundingClientRect(){return {left:0,top:0,right:100,bottom:100}},scrollIntoView(){}};elements.set(id,o);return o}
 const document={querySelector:el,querySelectorAll(){return []},createElement:n=>el('new-'+n),addEventListener(){},body:el('body'),documentElement:el('html')};let stored=C.clone(seed),writes=0;
 let previous=null;const storage={async restore(data,expectedRev){if(expectedRev!==undefined&&stored.rev!==expectedRev)throw Error('records changed');previous=C.clone(stored);writes++;stored={...C.clone(data),rev:stored.rev+1};return C.clone(stored)},async recover(){return this.restore(previous)},async init(){return C.clone(stored)},async get(){return C.clone(stored)},async resetMoney(){writes++;stored=C.resetMoney(stored);return C.clone(stored)},async mutate(action){writes++;stored=C.apply(stored,action);return C.clone(stored)}};
 const ctx={DIRHAYA_PREVIEW:preview,DirhayaCore:C,DirhayaI18n:require('../public/i18n.js'),DirhayaBackups:{...require('../public/backups.js')},DirhayaStorage:storage,DirhayaReminders:require('../public/reminders.js'),DirhayaSecurity:{enabled:()=>false,cancel(){}},document,console,window:null,navigator:{},location:{protocol:'file:'},innerWidth:440,innerHeight:956,matchMedia:()=>({matches:false}),setTimeout:()=>1,clearTimeout(){},FormData:class{constructor(form){this.values=form.values||{}}get(key){return this.values[key]??null}getAll(key){const value=this.values[key];return value==null?[]:Array.isArray(value)?value:[value]}},Date,Math,Promise,URL,Event:class{constructor(type){this.type=type}},File,Blob,addEventListener(){},scrollTo(){},isSecureContext:false};ctx.window=ctx;
 let src=fs.readFileSync(require.resolve('../public/app.js'),'utf8');src=src.replace(/init\(\);\s*\}\)\(\);\s*$/,`window.UI={persistError,inspectBackupFile,backupStatus,updateReason,tryAutoUpdate,autoCheckUpdates,init,render,dispatch,transactionForm,goalForm,accountForm,allocateForm,installSheet,sendMessage,checkOffline,refreshOfflineStatus,homeView,accountsView,goalsView,activityView,settingsView,chatView,get state(){return state},setState(s){state=s;realState=s},get messages(){return messages}};})();`);vm.runInNewContext(src,ctx);ctx.UI.setState(C.clone(seed));return {ctx,ui:ctx.UI,el,elements,get writes(){return writes},get stored(){return stored}};
}
test('all main views render from actual valid data without template exceptions',async()=>{const e=environment();for(const view of ['home','accounts','goals','activity','assistant']){await e.ui.dispatch('view:'+view);assert(e.el('#app').innerHTML.includes('غرس'));assert(!e.el('#app').innerHTML.includes('NaN'))}await e.ui.dispatch('settings');assert.match(e.el('#app').innerHTML,/Yours, on this device/)});
test('account and goal names are HTML escaped',()=>{const s=C.demo();s.accounts[0].name='<img src=x onerror=alert(1)>';s.goals[0].name='<script>bad</script>';const e=environment(s);assert.match(e.ui.accountsView(),/&lt;img/);assert(!e.ui.accountsView().includes('<img src=x'));assert.match(e.ui.goalsView(),/&lt;script&gt;/)});
test('demo mutations never overwrite actual saved records',async()=>{const s=C.blank(),e=environment(s);await e.ui.dispatch('demo');assert.equal(e.ui.state.accounts.length,3);await e.ui.dispatch('privacy');assert.equal(e.writes,0);assert.equal(e.stored.accounts.length,0);await e.ui.dispatch('exit-demo');assert.equal(e.ui.state.accounts.length,0)});
test('privacy toggle hides account values and removes prior chat messages',async()=>{const e=environment();await e.ui.dispatch('view:assistant');e.ui.sendMessage('balance');assert(e.ui.messages.length>0);await e.ui.dispatch('privacy');assert.equal(e.ui.messages.length,0);assert.match(e.ui.homeView(),/••••/);assert(!e.ui.accountsView().includes('8,302.00'))});
test('entry form defaults transfers to a different account',()=>{const e=environment();e.ui.transactionForm({kind:'transfer'});const html=e.el('#sheet').innerHTML,source=e.ui.state.accounts[0].id,destination=e.ui.state.accounts[1].id;const destinationSection=html.split('<select name="to"')[1].split('</select>')[0];assert(destinationSection.includes(`value="${destination}" selected`));assert(!destinationSection.includes(`value="${source}" selected`))});
test('all primary entry forms and detail sheets build correctly',async()=>{const e=environment();e.ui.accountForm();assert.match(e.el('#sheet').innerHTML,/Current balance/);e.ui.goalForm();assert.match(e.el('#sheet').innerHTML,/Target date/);e.ui.allocateForm(e.ui.state.goals[0].id);assert.match(e.el('#sheet').innerHTML,/Where the savings will be held/);assert.match(e.el('#sheet').innerHTML,/Take the money from/);await e.ui.dispatch('account:'+e.ui.state.accounts[0].id);assert.match(e.el('#sheet').innerHTML,/Check actual balance/);e.ui.installSheet();assert.match(e.el('#sheet').innerHTML,/preview/)});
test('separate cards, linked payments, and goal presets render',async()=>{let s=C.demo();s=C.apply(s,{type:'card.add',account:s.accounts[0].id,name:'Second debit',last4:'5678'});const e=environment(s);assert.match(e.ui.accountsView(),/Debit cards/);await e.ui.dispatch('card:'+s.cards[0].id);assert.match(e.el('#sheet').innerHTML,/counted once/);await e.ui.dispatch('card-entry:'+s.cards[0].id);assert.match(e.el('#sheet').innerHTML,new RegExp(`value="card:${s.cards[0].id}" selected`));await e.ui.dispatch('add-card');assert.match(e.el('#sheet').innerHTML,/Last four digits/);for(const key of ['china','car','marriage']){await e.ui.dispatch('goal-template:'+key);assert.match(e.el('#sheet').innerHTML,/value="(?:China trip|Car|Marriage)"/)}await e.ui.dispatch('move-goal:'+s.goals[0].id);assert.match(e.el('#sheet').innerHTML,/Record savings move/)});
test('balance check previews the gap and offers partial explanations',async()=>{let s=C.demo();const aid=s.accounts[0].id;s=C.apply(s,{type:'account.check',id:aid,balance:C.balances(s)[aid]-10000});const e=environment(s),unknown=s.transactions.find(t=>t.category==='Unexplained');await e.ui.dispatch('reconcile:'+aid);e.el('#actual-balance').oninput({target:{value:String((C.balances(s)[aid]-5000)/100)}});assert.match(e.el('#gap-preview').innerHTML,/50.00 unexplained spending/);await e.ui.dispatch('explain:'+unknown.id);assert.match(e.el('#sheet').innerHTML,/does not subtract it from your account again/);await e.ui.dispatch('unexplained');assert.match(e.el('#activity-results').innerHTML,/1 entry/);assert.match(e.ui.homeView(),/Known spending this month/)});

test('interactive preview labels its sample data and never saves mutations',async()=>{const e=environment(C.blank(),true);await e.ui.init();assert.match(e.el('#app').innerHTML,/Interactive preview · sample money · changes are not saved/);assert.match(e.el('#app').innerHTML,/Preview · not saved/);await e.ui.dispatch('privacy');assert.equal(e.writes,0);assert.equal(e.stored.accounts.length,0)});

test('split sheet previews and saves a date split through the actual form handler',async()=>{
 const e=environment(),t=e.ui.state.transactions.find(t=>t.type==='expense'),date=C.localDate(new Date(new Date().getFullYear(),new Date().getMonth()-1,15));
 const before=C.balances(e.ui.state);await e.ui.dispatch('transaction:'+t.id);assert.match(e.el('#sheet').innerHTML,/Split across months/);
 await e.ui.dispatch('split-transaction:'+t.id);assert.match(e.el('#sheet').innerHTML,/Date for this portion/);
 e.el('#split-amount').value='10';e.el('#split-date').value=date;e.el('#split-amount').oninput();assert.match(e.el('#split-preview').textContent,/10.00/);
 e.el('#split-form').values={amount:'10',date};await e.el('#split-form').onsubmit({preventDefault(){}});
 assert.equal(e.writes,1);assert.deepEqual(C.balances(e.ui.state),before);assert.equal(e.ui.state.transactions.find(x=>x.splitFrom===t.id).date,date);assert.equal(C.summary(e.ui.state,date).spent,1000);
});
test('explaining a portion exposes and submits the spending date',async()=>{
 let s=C.demo();s=C.apply(s,{type:'account.check',id:s.accounts[0].id,balance:C.balances(s)[s.accounts[0].id]-10000});const t=s.transactions.find(x=>x.category==='Unexplained'),e=environment(s),date=C.localDate(new Date(new Date().getFullYear(),new Date().getMonth()-1,15));
 await e.ui.dispatch('explain:'+t.id);assert.match(e.el('#sheet').innerHTML,/When did this happen/);assert.match(e.el('#sheet').innerHTML,new RegExp('value="'+t.date+'"'));
 e.el('#explain-form').values={amount:'25',category:'Transport',date,note:'Last month'};await e.el('#explain-form').onsubmit({preventDefault(){}});
 assert.equal(C.summary(e.ui.state,date).knownSpent,2500);assert.deepEqual(C.balances(e.ui.state),C.balances(s));
});

test('opening reset settings and cancelling never changes records',async()=>{const e=environment(),before=JSON.stringify(e.stored);await e.ui.dispatch('settings');assert.match(e.el('#app').innerHTML,/Reset balances &amp; history/);await e.ui.dispatch('reset-money');assert.match(e.el('#sheet').innerHTML,/account names and types/);assert.match(e.el('#sheet').innerHTML,/Type RESET/);await e.ui.dispatch('close');assert.equal(e.writes,0);assert.equal(JSON.stringify(e.stored),before)});
test('reset requires explicit confirmation and then clears numbers while keeping accounts',async()=>{const e=environment(),before=JSON.stringify(e.stored),ids=e.stored.accounts.map(a=>a.id);e.ui.sendMessage('balance');await e.ui.dispatch('reset-money');e.el('#reset-money-form').values={confirmation:'wrong'};await e.el('#reset-money-form').onsubmit({preventDefault(){}});assert.equal(e.writes,0);assert.equal(JSON.stringify(e.stored),before);e.el('#reset-money-form').values={confirmation:'RESET'};await e.el('#reset-money-form').onsubmit({preventDefault(){}});assert.equal(e.writes,1);assert.deepEqual(e.stored.accounts.map(a=>a.id),ids);assert.equal(C.summary(e.stored).total,0);assert.equal(e.stored.transactions.length,0);assert.equal(e.ui.messages.length,0);assert.match(e.el('#app').innerHTML,/Bank &amp; savings accounts|Bank & savings accounts/)});
test('resetting the demo leaves device records unchanged',async()=>{const e=environment(),before=JSON.stringify(e.stored);await e.ui.dispatch('demo');await e.ui.dispatch('reset-money');e.el('#reset-money-form').values={confirmation:'RESET'};await e.el('#reset-money-form').onsubmit({preventDefault(){}});assert.equal(C.summary(e.ui.state).total,0);assert.equal(e.writes,0);assert.equal(JSON.stringify(e.stored),before);await e.ui.dispatch('exit-demo');assert.equal(JSON.stringify(e.ui.state),before)});
test('retained accounts accept a starting balance through the form without adding income',async()=>{const e=environment(C.resetMoney(C.demo())),a=e.ui.state.accounts[0];await e.ui.dispatch('account:'+a.id);assert.match(e.el('#sheet').innerHTML,/Set starting balance/);await e.ui.dispatch('edit-account:'+a.id);assert.match(e.el('#sheet').innerHTML,/Starting balance · AED/);e.el('#account-form').values={name:a.name,kind:a.type,color:a.color,opening:'1234.56'};await e.el('#account-form').onsubmit({preventDefault(){}});assert.equal(C.summary(e.ui.state).total,123456);assert.equal(C.summary(e.ui.state).income,0);assert.equal(e.ui.state.transactions.length,0)});

test('overview graph filters period and account without writing money records',async()=>{let s=C.blank();for(const name of ['Bank','Cash'])s=C.apply(s,{type:'account.add',name,kind:'bank',opening:100000,color:'sand'});for(const [date,account,amount] of [['2026-07-01',s.accounts[0].id,12500],['2026-08-01',s.accounts[0].id,3300],['2026-07-01',s.accounts[1].id,5500]])s=C.apply(s,{type:'transaction.add',kind:'expense',amount,category:'Food & drink',account,date});const e=environment(s);await e.ui.dispatch('view:home');assert.match(e.el('#app').innerHTML,/Where your money goes/);e.el('#chart-month').onchange({target:{value:'2026-07'}});assert.match(e.el('#spending-chart').innerHTML,/180.00/);e.el('#chart-account').onchange({target:{value:s.accounts[0].id}});assert.match(e.el('#spending-chart').innerHTML,/125.00/);assert(!e.el('#spending-chart').innerHTML.includes('180.00'));e.el('#chart-month').onchange({target:{value:''}});assert.match(e.el('#spending-chart').innerHTML,/158.00/);assert.equal(e.writes,0)});
test('activity graph follows filters and privacy hides bar proportions and values',async()=>{const e=environment();await e.ui.dispatch('view:activity');assert.match(e.el('#activity-results').innerHTML,/Where this money goes/);e.el('#activity-type').onchange({target:{value:'income'}});assert.match(e.el('#activity-results').innerHTML,/No expenses or investment contributions/);await e.ui.dispatch('privacy');await e.ui.dispatch('view:home');assert.match(e.el('#spending-chart').innerHTML,/graph hidden/);assert(!e.el('#spending-chart').innerHTML.includes('width:'));assert(!e.el('#spending-chart').innerHTML.includes('AED'))});
test('investment account option and charts work with legacy data and reset',async()=>{const e=environment();e.ui.accountForm();assert.match(e.el('#sheet').innerHTML,/Investment account/);const s=C.resetMoney(e.ui.state);e.ui.setState(s);await e.ui.dispatch('view:home');assert.match(e.el('#spending-chart').innerHTML,/No expenses or investment contributions/);assert.equal(e.writes,0)});

function askDock(e,text){e.el('#dock-input').value=text;e.el('#dock-form').onsubmit({preventDefault(){}})}
test('floating helper stays in the modal and calculations preserve the expense form',async()=>{const e=environment();e.ui.transactionForm();const form=e.el('#sheet').innerHTML;e.el('input[name="amount"]').value='18';await e.ui.dispatch('dock-open');assert.equal(e.el('#assistant-dock').parentNode,e.el('#sheet'));askDock(e,'(120 + 45) / 3');assert.equal(e.ui.messages.at(-1).text,'55');assert.equal(e.el('#sheet').innerHTML,form);assert.equal(e.el('input[name="amount"]').value,'18');assert.equal(e.writes,0);await e.ui.dispatch('dock-minimise');await e.ui.dispatch('dock-open');assert.match(e.el('#assistant-dock').innerHTML,/55/);assert.equal(e.el('#sheet').innerHTML,form)});
test('Use amount explicitly fills the form but does not save an expense',async()=>{const e=environment();e.ui.transactionForm();await e.ui.dispatch('dock-open');askDock(e,'split 99 between 4');await e.ui.dispatch('dock-use');assert.equal(e.el('input[name="amount"]').value,'24.75');assert.equal(e.writes,0);assert.equal(e.el('#sheet').open,true)});
test('unfinished helper input survives minimise and closing the expense sheet',async()=>{const e=environment();e.ui.transactionForm();await e.ui.dispatch('dock-open');e.el('#dock-input').oninput({target:{value:'120 + '}});await e.ui.dispatch('dock-minimise');await e.ui.dispatch('close');assert.equal(e.el('#assistant-dock').parentNode,e.el('body'));await e.ui.dispatch('dock-open');assert.match(e.el('#assistant-dock').innerHTML,/value="120 \+ "/)});
test('ans works across full and floating chat and privacy clears it',async()=>{const e=environment();e.ui.sendMessage('20% off 150');await e.ui.dispatch('dock-open');askDock(e,'ans / 3');assert.equal(e.ui.messages.at(-1).text,'40');await e.ui.dispatch('privacy');assert.match(e.el('#assistant-dock').innerHTML,/Amounts are hidden/);await e.ui.dispatch('privacy');askDock(e,'ans * 2');assert.match(e.ui.messages.at(-1).text,/Calculate something first/)});
test('floating entry commands never replace an unfinished form or save records',async()=>{const e=environment();e.ui.transactionForm();const form=e.el('#sheet').innerHTML;await e.ui.dispatch('dock-open');askDock(e,'expense 5 from Cash for coffee');assert(e.ui.messages.at(-1).draft);assert.equal(e.el('#sheet').innerHTML,form);assert.match(e.el('#assistant-dock').innerHTML,/Finish or cancel your current form/);assert.equal(e.writes,0)});
test('negative, invalid and high precision answers do not overwrite expense amounts',async()=>{const e=environment();e.ui.transactionForm();e.el('input[name="amount"]').value='25';await e.ui.dispatch('dock-open');for(const q of ['1 - 5','1 / 3','1 / 0']){askDock(e,q);await e.ui.dispatch('dock-use');assert.equal(e.el('input[name="amount"]').value,'25')}assert.equal(e.writes,0)});
test('minimising full assistant returns to the prior page with input retained',async()=>{const e=environment();await e.ui.dispatch('view:accounts');await e.ui.dispatch('view:assistant');e.el('#chat-input').value='split 45 between 3';await e.ui.dispatch('dock-return');assert.match(e.el('#app').innerHTML,/Bank. Card. Cash. Clear/);await e.ui.dispatch('dock-open');assert.match(e.el('#assistant-dock').innerHTML,/value="split 45 between 3"/)});

function mockUpdate(e,build='dirhaya-v1-20990101-01',fail=false){let updates=0,reloads=0;const registration={active:null,addEventListener(){},async update(){updates++;if(fail)throw Error('offline')}};const worker={postMessage(_message,ports){ports[0].postMessage({ready:true,build})}};registration.active=worker;e.ctx.location={protocol:'https:',reload(){reloads++}};e.ctx.isSecureContext=true;e.ctx.navigator.serviceWorker={controller:worker,async register(){return registration}};e.ctx.MessageChannel=class{constructor(){this.port1={onmessage:null,close(){}};this.port2={postMessage:data=>this.port1.onmessage({data})}}};return {get updates(){return updates},get reloads(){return reloads}}}
test('manual update check requests fresh worker files without writes or a forced reload',async()=>{const e=environment(),m=mockUpdate(e);e.ui.transactionForm();const form=e.el('#sheet').innerHTML;await e.ui.checkOffline(true);e.ui.refreshOfflineStatus();assert.equal(m.updates,1);assert.equal(m.reloads,0);assert.equal(e.writes,0);assert.equal(e.el('#sheet').innerHTML,form);assert.equal(e.el('#update-notice').hidden,false);assert.match(e.el('#update-notice').innerHTML,/Update ready/)});
test('reload update requires confirmation and never clears saved records',async()=>{const e=environment(),m=mockUpdate(e);e.ctx.confirm=()=>false;await e.ui.dispatch('apply-update');assert.equal(m.reloads,0);e.ctx.confirm=()=>true;await e.ui.dispatch('apply-update');assert.equal(m.reloads,1);assert.equal(e.writes,0)});
test('same or older cached build does not create an update reload loop',async()=>{for(const build of ['dirhaya-v1-20260922-10','dirhaya-v1-20260922-09']){const e=environment();mockUpdate(e,build);await e.ui.checkOffline();e.ui.refreshOfflineStatus();assert.equal(e.el('#update-notice').hidden,true)}});
test('offline update failures preserve data and show a retry message',async()=>{const e=environment(),before=JSON.stringify(e.stored);mockUpdate(e,undefined,true);await e.ui.dispatch('check-offline');assert.match(e.el('#sheet').innerHTML,/Could not check for updates/);assert.equal(JSON.stringify(e.stored),before);assert.equal(e.writes,0)});

test('quick buttons open expense forms without recording anything',async()=>{const e=environment(),before=JSON.stringify(e.stored);for(const category of ['Food & drink','Transport','Laundry','Groceries','Bills','Shopping']){assert(e.ui.homeView().includes('quick-expense:'+category.replace('&','&amp;')));await e.ui.dispatch('quick-expense:'+category);assert.match(e.el('#sheet').innerHTML,/quick-expense-form/);assert.match(e.el('#sheet').innerHTML,/Save expense/);await e.ui.dispatch('close')}assert.equal(JSON.stringify(e.stored),before);assert.equal(e.writes,0);assert.match(e.ui.activityView(),/Quick expense/)});
test('quick entry saves exact amount, date and category and remembers payment after reopening',async()=>{const e=environment(),card=e.ui.state.cards[0],count=e.stored.transactions.length;await e.ui.dispatch('quick-expense:Laundry');e.el('#quick-expense-form').values={amount:'37.25',payment:'card:'+card.id,date:C.localDate(),note:'Weekly wash'};await e.el('#quick-expense-form').onsubmit({preventDefault(){}});assert.equal(e.stored.transactions.length,count+1);const t=e.stored.transactions.at(-1);assert.equal(t.amount,3725);assert.equal(t.category,'Laundry');assert.equal(t.account,card.account);assert.equal(t.card,card.id);assert.equal(t.note,'Weekly wash');const reopened=environment(e.stored);await reopened.ui.dispatch('quick-expense:Laundry');assert(reopened.el('#sheet').innerHTML.includes(`value="card:${card.id}" selected`));assert(!reopened.el('#sheet').innerHTML.includes('value="37.25"'))});
test('category-specific account takes priority over a newer expense elsewhere',async()=>{let s=C.demo();const cash=s.accounts.find(a=>a.type==='cash');s=C.apply(s,{type:'transaction.add',kind:'expense',amount:100,account:cash.id,date:C.localDate(),category:'Laundry'});s.transactions.at(-1).created=10;s=C.apply(s,{type:'transaction.add',kind:'expense',amount:100,account:s.accounts[0].id,date:C.localDate(),category:'Bills'});s.transactions.at(-1).created=20;const e=environment(s);await e.ui.dispatch('quick-expense:Laundry');assert(e.el('#sheet').innerHTML.includes(`value="${cash.id}" selected`))});
test('quick entries reject invalid amounts and guard duplicate submits',async()=>{const e=environment(),count=e.stored.transactions.length;await e.ui.dispatch('quick-expense:Transport');e.el('#quick-expense-form').values={amount:'0',payment:e.ui.state.accounts[0].id,date:C.localDate(),note:''};await e.el('#quick-expense-form').onsubmit({preventDefault(){}});assert.equal(e.stored.transactions.length,count);assert.equal(e.el('#sheet').open,true);e.el('#quick-expense-form').values.amount='5';const submit=e.el('#quick-expense-form').onsubmit;await Promise.all([submit({preventDefault(){}}),submit({preventDefault(){}})]);assert.equal(e.stored.transactions.length,count+1)});
test('quick form keeps calculator access and demo expense changes isolated',async()=>{const e=environment(),before=JSON.stringify(e.stored);await e.ui.dispatch('demo');await e.ui.dispatch('quick-expense:Groceries');const form=e.el('#sheet').innerHTML;await e.ui.dispatch('dock-open');askDock(e,'12 + 8');assert.equal(e.el('#sheet').innerHTML,form);e.el('#quick-expense-form').values={amount:'20',payment:e.ui.state.accounts[0].id,date:C.localDate(),note:''};await e.el('#quick-expense-form').onsubmit({preventDefault(){}});assert.equal(e.ui.state.transactions.at(-1).category,'Groceries');assert.equal(JSON.stringify(e.stored),before);assert.equal(e.writes,0)});
test('quick expense with no accounts opens account setup without saving',async()=>{const e=environment(C.blank());await e.ui.dispatch('quick-expense:Food & drink');assert.match(e.el('#sheet').innerHTML,/account-form/);assert.equal(e.writes,0)});

test('portfolio forms add a company with quantity and preserve total wealth on purchase',async()=>{let s=C.demo();s=C.apply(s,{type:'account.add',name:'Portfolio',kind:'investment',opening:0,color:'sage'});const e=environment(s),a=e.ui.state.accounts.at(-1),before=C.summary(s).total;assert.match(e.ui.accountsView(),/Add portfolio/);await e.ui.dispatch('add-holding:'+a.id);e.el('#holding-form').values={name:'Example company',quantity:'40',cost:'100',value:'100',mode:'transfer',source:s.accounts[0].id,funding:''};await e.el('#holding-form').onsubmit({preventDefault(){}});assert.equal(e.stored.accounts.at(-1).holdings[0].quantity,'40');assert.equal(C.summary(e.stored).total,before);await e.ui.dispatch('account:'+a.id);assert.match(e.el('#sheet').innerHTML,/Example company/);assert.match(e.el('#sheet').innerHTML,/40 shares/)});
test('portfolio valuation form changes current value without creating an expense',async()=>{let s=C.demo();s=C.apply(s,{type:'account.add',name:'Portfolio',kind:'investment',opening:10000,color:'sage'});const a=s.accounts.at(-1);s=C.apply(s,{type:'holding.add',account:a.id,name:'Fund',quantity:'25',cost:10000,value:10000,mode:'included'});const e=environment(s),h=s.accounts.at(-1).holdings[0],before=C.summary(s);await e.ui.dispatch('holding:'+a.id+':'+h.id);e.el('#holding-form').values={name:'Fund',quantity:'25',cost:'100',value:'110'};await e.el('#holding-form').onsubmit({preventDefault(){}});assert.equal(C.summary(e.stored).total,before.total+1000);assert.equal(C.summary(e.stored).spent,before.spent)});

test('locked startup does not read financial storage before verified unlock',async()=>{
 const e=environment();e.ui.setState(null);let reads=0;
 e.ctx.DirhayaSecurity.enabled=()=>true;
 e.ctx.DirhayaStorage.init=async()=>{reads++;return C.blank()};
 e.ctx.DirhayaSecurity.authenticate=async()=>{};
 await e.ui.init();assert.equal(reads,0);assert.equal(e.el('#lock-screen').open,true);
 await e.ui.dispatch('lock-unlock');assert.equal(reads,1);assert.equal(e.el('#lock-screen').open,false);assert.equal(e.writes,0);
});
test('lock preserves expense draft and cancellation blocks navigation',async()=>{
 const e=environment();e.ui.transactionForm({kind:'expense'});const draft=e.el('#sheet').innerHTML;
 await e.ui.dispatch('lock-now');await e.ui.dispatch('add-account');assert.equal(e.el('#sheet').innerHTML,draft);
 e.ctx.DirhayaSecurity.authenticate=async()=>{throw Object.assign(new Error('cancel'),{name:'NotAllowedError'})};
 await e.ui.dispatch('lock-unlock');assert.equal(e.el('#lock-screen').open,true);assert.match(e.el('#lock-error').textContent,/cancelled/);
 e.ctx.DirhayaSecurity.authenticate=async()=>{};await e.ui.dispatch('lock-unlock');
 assert.equal(e.el('#lock-screen').open,false);assert.equal(e.el('#sheet').open,true);assert.equal(e.el('#sheet').innerHTML,draft);assert.equal(e.writes,0);
});
test('storage failure after authentication stays visible on locked startup',async()=>{
 const e=environment();e.ui.setState(null);e.ctx.DirhayaSecurity.enabled=()=>true;e.ctx.DirhayaSecurity.authenticate=async()=>{};
 e.ctx.DirhayaStorage.init=async()=>{throw new Error('Storage unavailable')};
 await e.ui.init();await e.ui.dispatch('lock-unlock');assert.equal(e.el('#lock-screen').open,true);assert.match(e.el('#lock-error').textContent,/Storage unavailable/);
});
test('recovery failure stays locked and successful recovery leaves records unchanged',async()=>{
 const e=environment(),before=JSON.stringify(e.stored);await e.ui.dispatch('lock-now');
 e.ctx.DirhayaSecurity.recover=async()=>{throw new Error('Invalid recovery code')};
 await e.ui.dispatch('lock-recovery');assert.equal(e.el('#lock-screen').open,true);
 e.ctx.DirhayaSecurity.recover=async()=>{};await e.ui.dispatch('lock-recovery');
 assert.equal(e.el('#lock-screen').open,false);assert.equal(JSON.stringify(e.stored),before);assert.equal(e.writes,0);
});

test('new installation asks for its own name and saves it locally',async()=>{
 const e=environment(C.blank());await e.ui.init();assert.match(e.el('#sheet').innerHTML,/ما غرسناه/);await e.ui.dispatch('ghars-begin');assert.match(e.el('#sheet').innerHTML,/Welcome to Ghars/);
 const f=e.el('#welcome-name-form');f.values={name:'Aisha'};await f.onsubmit({preventDefault(){}});
 assert.equal(e.stored.settings.name,'Aisha');assert.equal(e.stored.settings.needsName,false);assert.equal(e.stored.settings.setupStep,1);assert.match(e.el('#sheet').innerHTML,/Your accounts &amp; current balances|Your accounts & current balances/);
 const again=environment(e.stored);await again.ui.init();assert.match(again.el('#sheet').innerHTML,/Your accounts/);
});
test('existing saved names remain unchanged with no onboarding prompt',async()=>{
 const s=C.blank();s.settings.name='Existing person';s.settings.gharsWelcomed=true;delete s.settings.needsName;
 const e=environment(s);await e.ui.init();assert.equal(e.el('#sheet').open,false);assert.equal(e.ui.state.settings.name,'Existing person');assert.equal(e.writes,0);
});

test('downloaded update applies once on idle overview without changing records',async()=>{
 const e=environment(),m=mockUpdate(e),values=new Map();e.ctx.sessionStorage={getItem:k=>values.get(k),setItem:(k,v)=>values.set(k,v)};
 await e.ui.checkOffline();assert.equal(e.ui.tryAutoUpdate(),false);
 assert.equal(e.ui.tryAutoUpdate(Date.now()+31000),true);e.ui.tryAutoUpdate(Date.now()+32000);
 assert.equal(m.reloads,1);assert.equal(e.writes,0);
});
test('automatic reload waits for expense draft, settings, calculator and lock',async()=>{
 for(const action of ['new-entry','settings','dock-open','lock-now']){
  const e=environment(),m=mockUpdate(e);e.ctx.sessionStorage={getItem:()=>null,setItem(){}};
  await e.ui.checkOffline();await e.ui.dispatch(action);
  assert.equal(e.ui.tryAutoUpdate(Date.now()+31000),false,action);assert.equal(m.reloads,0);
 }
});
test('automatic update avoids offline checks and repeated reload attempts',async()=>{
 const e=environment(),m=mockUpdate(e);e.ctx.navigator.onLine=false;await e.ui.autoCheckUpdates(true);assert.equal(m.updates,0);
 e.ctx.navigator.onLine=true;await e.ui.autoCheckUpdates(true);assert.equal(m.updates,1);
 e.ctx.sessionStorage={getItem:()=> '1',setItem(){}};assert.equal(e.ui.tryAutoUpdate(Date.now()+31000),false);assert.equal(m.reloads,0);
});

test('Ghars welcome precedes overview quote and preserves existing records',async()=>{
 const s=C.demo();s.settings.needsName=false;const e=environment(s),before=JSON.stringify(s.accounts);
 await e.ui.init();assert.match(e.el('#sheet').innerHTML,/ما غرسناه بالأمس بدأ اليوم يؤتي ثماره/);
 assert(!e.el('#sheet').innerHTML.includes('وعلينا أن نصبر'));
 await e.ui.dispatch('ghars-begin');assert.equal(e.el('#sheet').open,false);
 assert.match(e.ui.homeView(),/وعلينا أن نصبر ونواصل مسيرة البناء/);assert(!e.ui.homeView().includes('ما غرسناه'));
 assert.equal(JSON.stringify(e.stored.accounts),before);assert.deepEqual(e.stored.transactions,s.transactions);
 const again=environment(e.stored);await again.ui.init();assert.equal(again.el('#sheet').open,false);
});
test('night palette persists and backup validation keeps existing balances',async()=>{
 const e=environment(),before=C.balances(e.stored);await e.ui.dispatch('theme:night');
 assert.equal(e.stored.settings.theme,'night');assert.deepEqual(C.balances(e.stored),before);C.validate(JSON.parse(JSON.stringify(e.stored)));
 assert.match(e.ui.settingsView(),/data-action="theme:night"/);
});

test('custom quick buttons and default linked card drive both quick and normal expense forms',async()=>{const e=environment(),card=e.stored.cards[0];await e.ui.dispatch('quick-settings');e.el('#quick-settings-form').values={payment:'card:'+card.id,categories:['Laundry','Travel']};await e.el('#quick-settings-form').onsubmit({preventDefault(){}});assert.deepEqual(e.stored.settings.quickCategories,['Laundry','Travel']);assert(!e.ui.homeView().includes('quick-expense:Shopping'));for(const action of ['quick-expense:Laundry','new-entry']){await e.ui.dispatch(action);assert(e.el('#sheet').innerHTML.includes(`value="card:${card.id}" selected`))}assert.equal(e.stored.transactions.length,3)});
test('repeat expense opens today with original amount and account and waits for save',async()=>{const e=environment(),t=e.stored.transactions.find(t=>t.type==='expense'),before=JSON.stringify(e.stored);await e.ui.dispatch('transaction:'+t.id);assert.match(e.el('#sheet').innerHTML,/Repeat this expense/);await e.ui.dispatch('repeat-expense:'+t.id);assert.match(e.el('#sheet').innerHTML,new RegExp(`value="${C.localDate()}"`));assert(e.el('#sheet').innerHTML.includes(`value="${C.format(t.amount).replace(/,/g,'')}"`));assert.equal(JSON.stringify(e.stored),before);e.el('#transaction-form').values={amount:String(t.amount/100),account:t.card?'card:'+t.card:t.account,category:t.category,note:t.note,date:C.localDate()};await e.el('#transaction-form').onsubmit({preventDefault(){}});assert.equal(e.stored.transactions.length,3);assert.match(e.el('new-div').innerHTML,/Possible duplicate/);e.el('.duplicate-confirm').checked=true;await e.el('#transaction-form').onsubmit({preventDefault(){}});assert.equal(e.stored.transactions.length,4);assert.equal(e.stored.transactions.at(-1).id===t.id,false)});
test('start today form requires confirmation and preserves old activity with corrected balances',async()=>{const e=environment(),old=C.clone(e.stored),balances=C.balances(old);await e.ui.dispatch('start-today');e.el('#start-today-form').values=Object.fromEntries(old.accounts.map(a=>['balance:'+a.id,String(balances[a.id]/100)]));await e.el('#start-today-form').onsubmit({preventDefault(){}});assert.equal(JSON.stringify(e.stored),JSON.stringify(old));e.el('#start-today-form').values.confirmed='on';await e.el('#start-today-form').onsubmit({preventDefault(){}});assert.equal(e.stored.transactions.length,old.transactions.length);assert.equal(C.summary(e.stored).spent,0);assert.equal(C.summary(e.stored).salary,0);await e.ui.dispatch('view:activity');assert.match(e.el('#activity-results').innerHTML,/A good cup of coffee/);assert.match(e.ui.homeView(),/Earlier entries remain in Activity/)});
test('recurring salary is a pending draft until reviewed, and repeated form submission records once',async()=>{const e=environment(),before=C.summary(e.stored).total,account=e.stored.accounts[0].id;await e.ui.dispatch('new-recurring:Salary');e.el('#recurring-form').values={name:'Monthly salary',kind:'income',category:'Salary',amount:'1234',payment:account,frequency:'monthly',nextDate:C.localDate()};await e.el('#recurring-form').onsubmit({preventDefault(){}});assert.equal(C.summary(e.stored).total,before);const r=e.stored.recurring[0];await e.ui.dispatch('recurring');assert.match(e.el('#sheet').innerHTML,/1 schedules/);await e.ui.dispatch('review-recurring:'+r.id);assert.equal(C.summary(e.stored).total,before);e.el('#recurring-review-form').values={amount:'1250',payment:account,date:C.localDate(),note:'Actual salary'};const submit=e.el('#recurring-review-form').onsubmit;await Promise.all([submit({preventDefault(){}}),submit({preventDefault(){}})]);assert.equal(C.summary(e.stored).total,before+125000);assert.equal(e.stored.transactions.filter(t=>t.recurringId===r.id).length,1);assert.equal(C.dueRecurring(e.stored).length,0)});
test('plain export handoff is unverified until the saved copy is reopened; cancel does not report success',async()=>{const e=environment(),before=C.clone(e.stored),files=[];e.ctx.navigator.canShare=()=>true;e.ctx.navigator.share=async({files:f})=>{files.push(...f)};await e.ui.dispatch('create-backup');e.el('#backup-form').values={protection:'plain'};await e.el('#backup-form').onsubmit({preventDefault(){}});assert.equal(e.writes,0);assert.match(e.el('#sheet').innerHTML,/Save your backup/);e.ctx.navigator.share=async()=>{throw Object.assign(Error('Cancelled'),{name:'AbortError'})};await assert.rejects(e.ui.dispatch('save-backup'));assert.equal(e.stored.settings.lastExport,undefined);e.ctx.navigator.share=async({files:f})=>{files.push(...f)};await e.ui.dispatch('save-backup');assert.equal(files.length,1);assert(e.stored.settings.lastExport);assert.equal(e.stored.settings.lastVerifiedBackup,undefined);assert.match(e.el('#sheet').innerHTML,/Export requested/);await e.ui.inspectBackupFile(files[0],'verify');assert.match(e.el('#sheet').innerHTML,/Backup verified/);assert.equal(e.stored.settings.lastVerifiedBackup.digest,e.stored.settings.lastExport.digest);assert.deepEqual(e.stored.transactions,before.transactions);assert.deepEqual(e.stored.accounts,before.accounts);assert.deepEqual(e.stored.goals,before.goals)});
test('encrypted backup verification requires the saved password and never replaces finance records',async()=>{const e=environment(),before=C.clone(e.stored),B=require('../public/backups.js'),prepared=await B.create(before,{password:'test password 12345'}),file=new File([prepared.text],prepared.record.filename);await e.ui.inspectBackupFile(file,'verify');assert.match(e.el('#sheet').innerHTML,/unlock-backup-form/);e.el('#unlock-backup-form').values={password:'incorrect password'};await e.el('#unlock-backup-form').onsubmit({preventDefault(){}});assert.equal(e.stored.settings.lastVerifiedBackup,undefined);assert.equal(e.el('#sheet').open,true);e.el('#unlock-backup-form').values.password='test password 12345';await e.el('#unlock-backup-form').onsubmit({preventDefault(){}});assert.match(e.el('#sheet').innerHTML,/Backup verified/);assert.equal(e.stored.settings.lastVerifiedBackup.encrypted,true);assert.deepEqual(e.stored.transactions,before.transactions)});
test('restore validates, previews and requires confirmation before replacing records, with undo snapshot',async()=>{const e=environment(),original=C.clone(e.stored),other=C.blank();other.settings.name='Example family member';const file=new File([JSON.stringify(other)],'old.dirhaya');await assert.rejects(e.ui.inspectBackupFile(new File(['{}'],'invalid.json'),'restore'));assert.deepEqual(e.stored,original);await e.ui.inspectBackupFile(file,'restore');assert.match(e.el('#sheet').innerHTML,/Restore this backup/);e.el('#restore-form').values={};await e.el('#restore-form').onsubmit({preventDefault(){}});assert.deepEqual(e.stored,original);e.el('#restore-form').values.confirmed='on';await e.el('#restore-form').onsubmit({preventDefault(){}});assert.equal(e.stored.accounts.length,0);assert.equal(e.stored.settings.name,'Example family member');await e.ui.dispatch('recover');await e.el('#recover-form').onsubmit({preventDefault(){}});assert.deepEqual(e.stored.transactions,original.transactions);assert.deepEqual(e.stored.accounts,original.accounts)});
test('version status shows running version and explains pending updates while forms or assistant work are open',async()=>{const e=environment();mockUpdate(e);await e.ui.checkOffline();assert.match(e.ui.settingsView(),/Running version 1\.10\.1/);e.ui.transactionForm();assert.match(e.ui.updateReason(),/Close this screen/);await e.ui.dispatch('dock-open');assert.match(e.ui.updateReason(),/assistant/);assert.equal(e.ui.tryAutoUpdate(Date.now()+60000),false)});
test('verification storage failure after decryption is reported without claiming a verified backup',async()=>{const e=environment(),B=require('../public/backups.js'),prepared=await B.create(e.stored,{password:'verification password 123'});await e.ui.inspectBackupFile(new File([prepared.text],prepared.record.filename),'verify');e.ctx.DirhayaStorage.mutate=async()=>{throw Error('Simulated quota failure')};e.ctx.console={...console,error(){}};e.el('#unlock-backup-form').values={password:'verification password 123'};await e.el('#unlock-backup-form').onsubmit({preventDefault(){}});assert.equal(e.stored.settings.lastVerifiedBackup,undefined);assert.match(e.el('new-div').textContent,/could not be saved/);assert(!e.el('#sheet').innerHTML.includes('<h2 id="sheet-title">Backup verified'))});
test('a backup finishing decryption while locked keeps the lock dialog above new sheets',async()=>{const e=environment(),B=require('../public/backups.js'),prepared=await B.create(e.stored,{password:'background test password'});await e.ui.inspectBackupFile(new File([prepared.text],prepared.record.filename),'verify');e.el('#unlock-backup-form').values={password:'background test password'};const pending=e.el('#unlock-backup-form').onsubmit({preventDefault(){}});await e.ui.dispatch('lock-now');const shows=e.el('#lock-screen').modalShows;await pending;assert.equal(e.el('#lock-screen').open,true);assert(e.el('#lock-screen').modalShows>shows);await e.ui.dispatch('new-entry');assert.match(e.el('#sheet').innerHTML,/Backup verified/)});

test('guided setup resumes, sets an opening balance without income, and permits a clearly deferred backup',async()=>{const e=environment(C.blank());await e.ui.dispatch('setup-open');e.el('#welcome-name-form').values={name:'Family member',language:'ar',textSize:'large'};await e.el('#welcome-name-form').onsubmit({preventDefault(){}});assert.equal(e.stored.settings.language,'ar');assert.equal(e.stored.settings.textSize,'large');await e.ui.dispatch('setup-add-account');e.el('#setup-account-form').values={name:'Everyday account',kind:'bank',amount:'1250.50'};await e.el('#setup-account-form').onsubmit({preventDefault(){}});assert.equal(C.summary(e.stored).income,0);assert.equal(C.summary(e.stored).total,125050);assert.equal(e.stored.transactions.length,0);await e.el('#setup-accounts-form').onsubmit({preventDefault(){}});e.el('#setup-payment-form').values={payment:e.stored.accounts[0].id};await e.el('#setup-payment-form').onsubmit({preventDefault(){}});assert.equal(e.stored.settings.setupStep,3);assert.match(e.el('#sheet').innerHTML,/Create my first backup/);assert.equal(e.stored.settings.lastVerifiedBackup,undefined);await e.ui.dispatch('setup-step:4');await e.el('#finish-setup-form').onsubmit({preventDefault(){}});assert.equal(e.stored.settings.setupDone,true);assert.equal(C.backupReminder(e.stored).reason,'first');assert.equal(e.el('#sheet').open,false)});
test('favourite pre-fills a reviewable draft without a transaction until confirmed',async()=>{const e=environment(),a=e.stored.accounts[0];await e.ui.dispatch('add-favourite');e.el('#favourite-form').values={name:'Weekly laundry',amount:'30',category:'Laundry',payment:a.id,note:'Usual wash'};await e.el('#favourite-form').onsubmit({preventDefault(){}});assert.equal(e.stored.favourites.length,1);const count=e.stored.transactions.length;await e.ui.dispatch('use-favourite:'+e.stored.favourites[0].id);assert.equal(e.stored.transactions.length,count);assert.match(e.el('#sheet').innerHTML,/value="30.00"/);assert.match(e.el('#sheet').innerHTML,/<option selected>Laundry<\/option>/);e.el('#transaction-form').values={amount:'30',account:a.id,category:'Laundry',note:'Usual wash',date:C.localDate()};await e.el('#transaction-form').onsubmit({preventDefault(){}});assert.equal(e.stored.transactions.length,count+1)});
test('changing a warned draft invalidates prior duplicate acknowledgement',async()=>{const e=environment(),t=e.stored.transactions.find(t=>t.type==='expense');await e.ui.dispatch('repeat-expense:'+t.id);const f=e.el('#transaction-form');f.values={amount:String(t.amount/100),account:t.card?'card:'+t.card:t.account,category:t.category,note:t.note,date:C.localDate()};await f.onsubmit({preventDefault(){}});assert.match(e.el('new-div').innerHTML,/Possible duplicate/);e.el('.duplicate-confirm').checked=true;f.values.note='Changed draft';await f.onsubmit({preventDefault(){}});assert.equal(e.stored.transactions.length,3);assert.match(e.el('new-div').innerHTML,/Possible duplicate/);e.el('.duplicate-confirm').checked=true;await f.onsubmit({preventDefault(){}});assert.equal(e.stored.transactions.length,4)});
test('already recorded UI links a reviewed payment without touching balances',async()=>{let s=C.demo();const t=s.transactions.find(t=>t.type==='expense');s=C.apply(s,{type:'recurring.save',name:'Usual payment',kind:'expense',category:t.category,amount:t.amount,account:t.account,frequency:'monthly',nextDate:t.date});const e=environment(s),before=C.balances(s),r=s.recurring[0];await e.ui.dispatch('review-recurring:'+r.id);assert.match(e.el('#sheet').innerHTML,/Already recorded/);await e.ui.dispatch('match-recurring:'+r.id);e.el('#match-recurring-form').values={transaction:t.id,confirmed:'on'};await e.el('#match-recurring-form').onsubmit({preventDefault(){}});assert.equal(e.stored.transactions.length,s.transactions.length);assert.deepEqual(C.balances(e.stored),before);assert.equal(e.stored.transactions.find(x=>x.id===t.id).recurringId,r.id)});
test('undo screen identifies the latest change and confirmation preserves preferences',async()=>{let s=C.demo();s=C.apply(s,{type:'transaction.delete',id:s.transactions[1].id});const e=environment(s);await e.ui.dispatch('undo-panel');assert.match(e.el('#sheet').innerHTML,/Entry deleted/);await e.el('#undo-form').onsubmit({preventDefault(){}});assert.equal(e.stored.transactions.length,3);assert.deepEqual(e.stored.settings,s.settings)});
test('reading controls persist direction and size without changing records',async()=>{const e=environment(),old=JSON.stringify(e.stored.transactions);await e.ui.dispatch('reading');e.el('#reading-form').values={language:'ar',textSize:'larger'};await e.el('#reading-form').onsubmit({preventDefault(){}});assert.equal(e.stored.settings.language,'ar');assert.equal(e.el('html').dir,'rtl');assert.equal(e.el('html').lang,'ar');assert.equal(JSON.stringify(e.stored.transactions),old);await e.ui.dispatch('reading');e.el('#reading-form').values={language:'en',textSize:'standard'};await e.el('#reading-form').onsubmit({preventDefault(){}});assert.equal(e.el('html').dir,'ltr')});

test('business errors mentioning transactions do not become misleading storage errors',()=>{const e=environment();for(const message of ['This account has transactions or goal savings. Keep it to preserve your history.','This transaction no longer exists.','Invalid transaction.'])assert.equal(e.ui.persistError(new Error(message)),message);for(const name of ['QuotaExceededError','UnknownError','TransactionInactiveError']){const error=new Error('write failed');error.name=name;assert.match(e.ui.persistError(error),/check device storage/)}assert.match(e.ui.persistError(new Error('Simulated quota error')),/check device storage/)});
test('unused account deletion names linked cards and requires explicit checkbox before removing them',async()=>{let s=C.blank();s=C.apply(s,{type:'account.add',name:'Unused',kind:'bank',opening:1234});s=C.apply(s,{type:'card.add',name:'Unused debit',account:s.accounts[0].id});const e=environment(s);await e.ui.dispatch('delete-account:'+s.accounts[0].id);assert.match(e.el('#sheet').innerHTML,/Unused debit/);assert.match(e.el('#sheet').innerHTML,/12.34/);await e.el('#delete-account-form').onsubmit({preventDefault(){}});assert.equal(e.writes,0);assert.match(e.el('new-div').textContent,/Confirm removal/);e.el('#delete-account-form').values={removeCards:'on'};await e.el('#delete-account-form').onsubmit({preventDefault(){}});assert.equal(e.stored.accounts.length,0);assert.equal(e.stored.cards.length,0)});
test('used account deletion shows actionable blockers without attempting any save',async()=>{const e=environment(),id=e.stored.accounts[0].id,before=JSON.stringify(e.stored);await e.ui.dispatch('delete-account:'+id);assert.match(e.el('#sheet').innerHTML,/Account is still linked/);assert.match(e.el('#sheet').innerHTML,/See this account’s activity/);assert(!e.el('#sheet').innerHTML.includes('id="delete-account-form"'));assert.equal(e.writes,0);assert.equal(JSON.stringify(e.stored),before)});
test('unused account without linked cards deletes through confirmation and can be undone',async()=>{let s=C.blank();s=C.apply(s,{type:'account.add',name:'Empty account',kind:'cash',opening:0});const e=environment(s);await e.ui.dispatch('delete-account:'+s.accounts[0].id);assert(!e.el('#sheet').innerHTML.includes('name="removeCards"'));assert.equal(e.writes,0);await e.el('#delete-account-form').onsubmit({preventDefault(){}});assert.equal(e.stored.accounts.length,0);await e.ui.dispatch('undo-panel');await e.el('#undo-form').onsubmit({preventDefault(){}});assert.deepEqual(e.stored.accounts,s.accounts)});
